var todosNos = [
    // ========== NÍVEL 1: SISTEMAS DE CLASSIFICAÇÃO E TEMPO ==========
    // Categoria: Ideia (Títulos) — linhas calculadas automaticamente
    { id: '50', level: 1, categoria: 'ideia', label: 'MÁRTIR', grupo: 'ideia', font: { color: '#ffaaaa', size: 13, bold: true } },
    { id: '51', level: 1, categoria: 'ideia', label: 'DOUTOR', grupo: 'ideia', font: { color: '#ffffaa', size: 13, bold: true } },
    { id: '52', level: 1, categoria: 'ideia', label: 'VIRGEM', grupo: 'ideia', font: { color: '#ffffff', size: 13, bold: true } },
    { id: '53', level: 1, categoria: 'ideia', label: 'CONFESSOR', grupo: 'ideia', font: { color: '#aaffaa', size: 13, bold: true } },
    { id: '54', level: 1, categoria: 'ideia', label: 'PENITENTE', grupo: 'ideia', font: { color: '#e6b3ff', size: 13, bold: true } },
    { id: '56', level: 1, categoria: 'ideia', label: 'PAPA', grupo: 'ideia', font: { color: '#ffd700', size: 13, bold: true } },
    { id: '57', level: 1, categoria: 'ideia', label: 'BISPO', grupo: 'ideia', font: { color: '#dca3ff', size: 13, bold: true } },
    { id: '59', level: 1, categoria: 'ideia', label: 'ABADE', grupo: 'ideia', font: { color: '#ffb366', size: 13, bold: true } },
    { id: '60', level: 1, categoria: 'ideia', label: 'VIÚVA', grupo: 'ideia', font: { color: '#ff99cc', size: 13, bold: true } },
    { id: '58', level: 1, categoria: 'ideia', label: 'ARCANJO', grupo: 'ideia', font: { color: '#a3e4ff', size: 13, bold: true } },
    
    // Categoria: Documento (Meses) — linhas calculadas automaticamente
    { id: '70', level: 1, categoria: 'documento', label: 'JANEIRO', grupo: 'documento', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '80', level: 1, categoria: 'documento', label: 'FEVEREIRO', grupo: 'documento', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '90', level: 1, categoria: 'documento', label: 'MARÇO', grupo: 'documento', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '91', level: 1, categoria: 'documento', label: 'ABRIL', grupo: 'documento', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '92', level: 1, categoria: 'documento', label: 'MAIO', grupo: 'documento', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '93', level: 1, categoria: 'documento', label: 'JUNHO', grupo: 'documento', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '94', level: 1, categoria: 'documento', label: 'JULHO', grupo: 'documento', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '95', level: 1, categoria: 'documento', label: 'AGOSTO', grupo: 'documento', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '96', level: 1, categoria: 'documento', label: 'SETEMBRO', grupo: 'documento', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '97', level: 1, categoria: 'documento', label: 'OUTUBRO', grupo: 'documento', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '98', level: 1, categoria: 'documento', label: 'NOVEMBRO', grupo: 'documento', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '99', level: 1, categoria: 'documento', label: 'DEZEMBRO', grupo: 'documento', font: { color: '#ffffff', size: 14, bold: true } },

    // ========== NÍVEL 2: SANTOS BÍBLICOS / FUNDADORES (26 nós -> corta em f0 e f1) ==========
    { id: '4',   level: 2, label: 'S. José', grupo: 'pessoa', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '71',  level: 2, label: 'S. João Batista', grupo: 'pessoa', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '2',   level: 2, label: 'S. Pedro', grupo: 'pessoa', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '3',   level: 2, label: 'S. Paulo', grupo: 'pessoa', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '55',  level: 2, label: 'S. João', grupo: 'pessoa', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '86',  level: 2, label: 'S. Matias', grupo: 'pessoa', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '110', level: 2, label: 'S. André', grupo: 'pessoa', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '111', level: 2, label: 'S. Tiago Maior', grupo: 'pessoa', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '112', level: 2, label: 'S. Filipe', grupo: 'pessoa', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '113', level: 2, label: 'S. Bartolomeu', grupo: 'pessoa', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '114', level: 2, label: 'S. Tomé', grupo: 'pessoa', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '115', level: 2, label: 'S. Mateus', grupo: 'pessoa', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '116', level: 2, label: 'S. Tiago Menor', grupo: 'pessoa', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '117', level: 2, label: 'S. Tadeu', grupo: 'pessoa', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '118', level: 2, label: 'S. Simão', grupo: 'pessoa', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '228', level: 2, label: 'S. Barnabé', grupo: 'pessoa', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '215', level: 2, label: 'Sta. Maria Madalena', grupo: 'pessoa', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '218', level: 2, label: 'Sta. Ana', grupo: 'pessoa', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '221', level: 2, label: 'Sta. Marta', grupo: 'pessoa', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '412', level: 2, label: 'S. Timóteo', grupo: 'pessoa', font: { color: '#ffffff', size: 14, bold: true } },
    // Quebra para > 20
    { id: '418', level: 2, label: 'S. Tito', grupo: 'pessoa', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '424', level: 2, label: 'N. Sra. de Lourdes', grupo: 'pessoa', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '439', level: 2, label: 'S. Gabriel Arcanjo', grupo: 'pessoa', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '440', level: 2, label: 'N. Sra. da Anunciação', grupo: 'pessoa', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '441', level: 2, label: 'N. Sra. das Sete Dores', grupo: 'pessoa', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '453', level: 2, label: 'S. Marcos Evangelista', grupo: 'pessoa', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '603', level: 2, label: 'S. Miguel Arcanjo', grupo: 'pessoa', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '630', level: 2, label: 'Sto. Estêvão, Protomártir', grupo: 'pessoa', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '631', level: 2, label: 'N. Sra. das Neves', grupo: 'pessoa', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '632', level: 2, label: 'Transfiguração do Senhor', grupo: 'pessoa', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '638', level: 2, label: 'Assunção de Maria', grupo: 'pessoa', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '639', level: 2, label: 'S. Joaquim', grupo: 'pessoa', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '644', level: 2, label: 'Imaculado Coração', grupo: 'pessoa', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '680', level: 2, label: 'S. Lucas Evangelista', grupo: 'pessoa', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '685', level: 2, label: 'S. Rafael Arcanjo', grupo: 'pessoa', font: { color: '#ffffff', size: 14, bold: true } },
    { id: '718', level: 2, label: 'Santos Inocentes', grupo: 'pessoa', font: { color: '#ffffff', size: 14, bold: true } },

    // ========== NÍVEL 3: ANTIGUIDADE (Séc I ao V) (nós — linhas calculadas automaticamente) ==========
    { id: '73', level: 3, label: 'Sta. Inês', grupo: 'pessoa' },
    { id: '72', level: 3, label: 'S. Sebastião', grupo: 'pessoa' },
    { id: '7',  level: 3, label: 'S. Jorge', grupo: 'pessoa' },
    { id: '76', level: 3, label: 'S. Paulo Eremita', grupo: 'pessoa' },
    { id: '74', level: 3, label: 'S. Antão', grupo: 'pessoa' },
    { id: '64', level: 3, label: 'Sta. Mônica', grupo: 'pessoa' },
    { id: '5',  level: 3, label: 'S. Agostinho', grupo: 'pessoa' },
    { id: '81', level: 3, label: 'S. Inácio de Antioquia', grupo: 'pessoa' },
    { id: '82', level: 3, label: 'S. Brás', grupo: 'pessoa' },
    { id: '83', level: 3, label: 'Sta. Águeda', grupo: 'pessoa' },
    { id: '84', level: 3, label: 'S. Valentim', grupo: 'pessoa' },
    { id: '204', level: 3, label: '7 Irmãos, Rufina e Secunda', grupo: 'pessoa' },
    { id: '205', level: 3, label: 'S. Pio I', grupo: 'pessoa' },
    { id: '207', level: 3, label: 'S. Anacleto', grupo: 'pessoa' },
    { id: '210', level: 3, label: 'Sto. Aleixo', grupo: 'pessoa' },
    { id: '214', level: 3, label: 'Sta. Práxedes', grupo: 'pessoa' },
    { id: '216', level: 3, label: 'Sto. Apolinário', grupo: 'pessoa' },
    { id: '217', level: 3, label: 'Sta. Cristina', grupo: 'pessoa' },
    { id: '219', level: 3, label: 'S. Pantaleão', grupo: 'pessoa' },
    { id: '220', level: 3, label: 'Nazário e Celso', grupo: 'pessoa' },
    { id: '222', level: 3, label: 'Abdon e Sennen', grupo: 'pessoa' },
    { id: '223', level: 3, label: 'Marcelino, Pedro e Erasmo', grupo: 'pessoa' },
    { id: '226', level: 3, label: 'Primo e Feliciano', grupo: 'pessoa' },
    { id: '229', level: 3, label: 'S. Basílio Magno', grupo: 'pessoa' },
    { id: '230', level: 3, label: 'Vito, Modesto e Crescência', grupo: 'pessoa' },
    { id: '231', level: 3, label: 'Sto. Efrém', grupo: 'pessoa' },
    { id: '233', level: 3, label: 'Gervásio e Protásio', grupo: 'pessoa' },
    { id: '236', level: 3, label: 'S. Paulino de Nola', grupo: 'pessoa' },
    { id: '237', level: 3, label: 'João e Paulo', grupo: 'pessoa' },
    { id: '239', level: 3, label: 'Sto. Irineu', grupo: 'pessoa' },
    { id: '400', level: 3, label: 'S. Higino', grupo: 'pessoa' },
    { id: '401', level: 3, label: 'S. Hilário de Poitiers', grupo: 'pessoa' },
    { id: '402', level: 3, label: 'S. Félix de Nola', grupo: 'pessoa' },
    { id: '404', level: 3, label: 'S. Marcelo I', grupo: 'pessoa' },
    { id: '405', level: 3, label: 'Sta. Prisca', grupo: 'pessoa' },
    { id: '406', level: 3, label: 'Mário, Marta, Audifax e Abaco', grupo: 'pessoa' },
    { id: '408', level: 3, label: 'S. Fabiano', grupo: 'pessoa' },
    { id: '409', level: 3, label: 'Vicente e Anastácio', grupo: 'pessoa' },
    { id: '411', level: 3, label: 'Sta. Emerenciana', grupo: 'pessoa' },
    { id: '413', level: 3, label: 'S. Policarpo', grupo: 'pessoa' },
    { id: '414', level: 3, label: 'S. João Crisóstomo', grupo: 'pessoa' },
    { id: '416', level: 3, label: 'Sta. Martinha', grupo: 'pessoa' },
    { id: '419', level: 3, label: 'Sta. Dorotéia', grupo: 'pessoa' },
    { id: '422', level: 3, label: 'S. Cirilo de Alexandria', grupo: 'pessoa' },
    { id: '423', level: 3, label: 'Sta. Apolônia', grupo: 'pessoa' },
    { id: '426', level: 3, label: 'Faustino e Jovita', grupo: 'pessoa' },
    { id: '427', level: 3, label: 'S. Simeão', grupo: 'pessoa' },
    { id: '431', level: 3, label: 'S. Lúcio I', grupo: 'pessoa' },
    { id: '432', level: 3, label: 'Perpétua e Felicidade', grupo: 'pessoa' },
    { id: '435', level: 3, label: 'Quarenta Mártires', grupo: 'pessoa' },
    { id: '438', level: 3, label: 'S. Cirilo de Jerusalém', grupo: 'pessoa' },
    { id: '445', level: 3, label: 'S. Leão Magno', grupo: 'pessoa' },
    { id: '447', level: 3, label: 'S. Justino', grupo: 'pessoa' },
    { id: '448', level: 3, label: 'Tibúrcio, Valeriano e Máximo', grupo: 'pessoa' },
    { id: '449', level: 3, label: 'S. Aniceto', grupo: 'pessoa' },
    { id: '451', level: 3, label: 'Sotero e Caio', grupo: 'pessoa' },
    { id: '454', level: 3, label: 'Cleto e Marcelino', grupo: 'pessoa' },
    { id: '457', level: 3, label: 'S. Vital', grupo: 'pessoa' },
    { id: '600', level: 3, label: 'Sto. Atanásio', grupo: 'pessoa' },
    { id: '604', level: 3, label: 'S. Gregório Nazianzeno', grupo: 'pessoa' },
    { id: '606', level: 3, label: 'Gordiano e Epímaco', grupo: 'pessoa' },
    { id: '607', level: 3, label: 'Nereu, Aquileu, Domitila...', grupo: 'pessoa' },
    { id: '613', level: 3, label: 'S. Venâncio', grupo: 'pessoa' },
    { id: '615', level: 3, label: 'Sta. Pudenciana', grupo: 'pessoa' },
    { id: '618', level: 3, label: 'S. Urbano I', grupo: 'pessoa' },
    { id: '620', level: 3, label: 'S. Eleutério', grupo: 'pessoa' },
    { id: '625', level: 3, label: 'S. Félix I', grupo: 'pessoa' },
    { id: '628', level: 3, label: 'Sta. Petronila', grupo: 'pessoa' },
    { id: '634', level: 3, label: 'Ciríaco, Largo e Esmaragdo', grupo: 'pessoa' },
    { id: '635', level: 3, label: 'S. Lourenço', grupo: 'pessoa' },
    { id: '636', level: 3, label: 'Tibúrcio e Susana', grupo: 'pessoa' },
    { id: '637', level: 3, label: 'Hipólito e Cassiano', grupo: 'pessoa' },
    { id: '641', level: 3, label: 'S. Agapito', grupo: 'pessoa' },
    { id: '647', level: 3, label: 'S. Zeferino', grupo: 'pessoa' },
    { id: '652', level: 3, label: 'Doze Santos Irmãos', grupo: 'pessoa' },
    { id: '655', level: 3, label: 'S. Gorgônio', grupo: 'pessoa' },
    { id: '657', level: 3, label: 'Proto e Jacinto', grupo: 'pessoa' },
    { id: '658', level: 3, label: 'Cornélio e Cipriano', grupo: 'pessoa' },
    { id: '660', level: 3, label: 'S. Januário e Comp.', grupo: 'pessoa' },
    { id: '661', level: 3, label: 'Eustáquio e Comp.', grupo: 'pessoa' },
    { id: '663', level: 3, label: 'S. Maurício e Comp.', grupo: 'pessoa' },
    { id: '664', level: 3, label: 'S. Lino', grupo: 'pessoa' },
    { id: '665', level: 3, label: 'Cipriano e Justina', grupo: 'pessoa' },
    { id: '666', level: 3, label: 'Cosme e Damião', grupo: 'pessoa' },
    { id: '668', level: 3, label: 'S. Jerônimo', grupo: 'pessoa' },
    { id: '674', level: 3, label: 'Dionísio, Rústico e Eleutério', grupo: 'pessoa' },
    { id: '677', level: 3, label: 'S. Calisto I', grupo: 'pessoa' },
    { id: '683', level: 3, label: 'S. Hilarião', grupo: 'pessoa' },
    { id: '684', level: 3, label: 'Sta. Úrsula e Comp.', grupo: 'pessoa' },
    { id: '686', level: 3, label: 'Crisanto e Daria', grupo: 'pessoa' },
    { id: '687', level: 3, label: 'S. Evaristo', grupo: 'pessoa' },
    { id: '690', level: 3, label: 'Quatro Coroados', grupo: 'pessoa' },
    { id: '691', level: 3, label: 'S. Teodoro', grupo: 'pessoa' },
    { id: '693', level: 3, label: 'S. Martinho de Tours', grupo: 'pessoa' },
    { id: '699', level: 3, label: 'S. Gregório Taumaturgo', grupo: 'pessoa' },
    { id: '701', level: 3, label: 'Sta. Cecília', grupo: 'pessoa' },
    { id: '702', level: 3, label: 'S. Clemente I', grupo: 'pessoa' },
    { id: '703', level: 3, label: 'Sta. Felicidade', grupo: 'pessoa' },
    { id: '704', level: 3, label: 'S. Crisógono', grupo: 'pessoa' },
    { id: '705', level: 3, label: 'Sta. Catarina de Alexandria', grupo: 'pessoa' },
    { id: '707', level: 3, label: 'S. Pedro de Alexandria', grupo: 'pessoa' },
    { id: '708', level: 3, label: 'S. Saturnino', grupo: 'pessoa' },
    { id: '709', level: 3, label: 'Sta. Bibiana', grupo: 'pessoa' },
    { id: '710', level: 3, label: 'S. Pedro Crisólogo', grupo: 'pessoa' },
    { id: '712', level: 3, label: 'S. Nicolau', grupo: 'pessoa' },
    { id: '713', level: 3, label: 'Sto. Ambrósio', grupo: 'pessoa' },
    { id: '714', level: 3, label: 'S. Melquíades', grupo: 'pessoa' },
    { id: '715', level: 3, label: 'S. Dâmaso I', grupo: 'pessoa' },
    { id: '716', level: 3, label: 'Sta. Luzia', grupo: 'pessoa' },
    { id: '720', level: 3, label: 'S. Silvestre I', grupo: 'pessoa' },

    // ========== NÍVEL 4: IDADE MÉDIA (Séc VI ao XV) (nós — linhas calculadas automaticamente) ==========
    { id: '6',  level: 4, label: 'S. Bento', grupo: 'pessoa' },
    { id: '85', level: 4, label: 'Sta. Escolástica', grupo: 'pessoa' },
    { id: '66', level: 4, label: 'S. Bernardo', grupo: 'pessoa' },
    { id: '8',  level: 4, label: 'S. Francisco', grupo: 'pessoa' },
    { id: '11', level: 4, label: 'Sta. Clara', grupo: 'pessoa' },
    { id: '9',  level: 4, label: 'S. Domingos', grupo: 'pessoa' },
    { id: '10', level: 4, label: 'S. Tomás de Aquino', grupo: 'pessoa' },
    { id: '65', level: 4, label: 'Sto. Antônio', grupo: 'pessoa' },
    { id: '67', level: 4, label: 'Sta. Rita', grupo: 'pessoa' },
    { id: '200', level: 4, label: 'S. Leão II', grupo: 'pessoa' },
    { id: '202', level: 4, label: 'Cirilo e Metódio', grupo: 'pessoa' },
    { id: '203', level: 4, label: 'Sta. Isabel', grupo: 'pessoa' },
    { id: '206', level: 4, label: 'S. João Gualberto', grupo: 'pessoa' },
    { id: '208', level: 4, label: 'S. Boaventura', grupo: 'pessoa' },
    { id: '209', level: 4, label: 'Sto. Henrique', grupo: 'pessoa' },
    { id: '224', level: 4, label: 'S. Bonifácio', grupo: 'pessoa' },
    { id: '225', level: 4, label: 'S. Norberto', grupo: 'pessoa' },
    { id: '227', level: 4, label: 'Sta. Margarida', grupo: 'pessoa' },
    { id: '232', level: 4, label: 'Sta. Juliana', grupo: 'pessoa' },
    { id: '234', level: 4, label: 'S. Silvério', grupo: 'pessoa' },
    { id: '238', level: 4, label: 'S. Guilherme', grupo: 'pessoa' },
    { id: '403', level: 4, label: 'S. Mauro', grupo: 'pessoa' },
    { id: '407', level: 4, label: 'S. Canuto', grupo: 'pessoa' },
    { id: '410', level: 4, label: 'S. Raimundo de Penaforte', grupo: 'pessoa' },
    { id: '415', level: 4, label: 'S. Pedro Nolasco', grupo: 'pessoa' },
    { id: '417', level: 4, label: 'Sto. André Corsini', grupo: 'pessoa' },
    { id: '420', level: 4, label: 'S. Romualdo', grupo: 'pessoa' },
    { id: '421', level: 4, label: 'S. João da Mata', grupo: 'pessoa' },
    { id: '425', level: 4, label: '7 Fundadores Servitas', grupo: 'pessoa' },
    { id: '428', level: 4, label: 'S. Pedro Damião', grupo: 'pessoa' },
    { id: '430', level: 4, label: 'S. Casimiro', grupo: 'pessoa' },
    { id: '434', level: 4, label: 'Sta. Francisca Romana', grupo: 'pessoa' },
    { id: '436', level: 4, label: 'S. Gregório Magno', grupo: 'pessoa' },
    { id: '437', level: 4, label: 'S. Patrício', grupo: 'pessoa' },
    { id: '442', level: 4, label: 'S. João Damasceno', grupo: 'pessoa' },
    { id: '443', level: 4, label: 'Sto. Isidoro', grupo: 'pessoa' },
    { id: '444', level: 4, label: 'S. Vicente Férrer', grupo: 'pessoa' },
    { id: '446', level: 4, label: 'S. Hermenegildo', grupo: 'pessoa' },
    { id: '450', level: 4, label: 'Sto. Anselmo', grupo: 'pessoa' },
    { id: '458', level: 4, label: 'S. Pedro de Verona', grupo: 'pessoa' },
    { id: '459', level: 4, label: 'Sta. Catarina de Sena', grupo: 'pessoa' },
    { id: '602', level: 4, label: 'Sto. Estanislau', grupo: 'pessoa' },
    { id: '605', level: 4, label: 'Sto. Antonino', grupo: 'pessoa' },
    { id: '611', level: 4, label: 'S. Ubaldo', grupo: 'pessoa' },
    { id: '614', level: 4, label: 'S. Pedro Celestino', grupo: 'pessoa' },
    { id: '616', level: 4, label: 'S. Bernardino de Sena', grupo: 'pessoa' },
    { id: '617', level: 4, label: 'S. Gregório VII', grupo: 'pessoa' },
    { id: '621', level: 4, label: 'S. Beda, o Venerável', grupo: 'pessoa' },
    { id: '622', level: 4, label: 'S. João I', grupo: 'pessoa' },
    { id: '623', level: 4, label: 'Sto. Agostinho de Cantuária', grupo: 'pessoa' },
    { id: '626', level: 4, label: 'Sta. Joana d\'Arc', grupo: 'pessoa' },
    { id: '627', level: 4, label: 'S. Fernando III', grupo: 'pessoa' },
    { id: '640', level: 4, label: 'S. Jacinto', grupo: 'pessoa' },
    { id: '645', level: 4, label: 'S. Filipe Benício', grupo: 'pessoa' },
    { id: '646', level: 4, label: 'S. Luís IX', grupo: 'pessoa' },
    { id: '650', level: 4, label: 'S. Raimundo Nonato', grupo: 'pessoa' },
    { id: '651', level: 4, label: 'Sto. Egídio', grupo: 'pessoa' },
    { id: '653', level: 4, label: 'Sto. Estêvão (Rei)', grupo: 'pessoa' },
    { id: '654', level: 4, label: 'S. Lourenço Justiniano', grupo: 'pessoa' },
    { id: '656', level: 4, label: 'S. Nicolau de Tolentino', grupo: 'pessoa' },
    { id: '667', level: 4, label: 'S. Venceslau', grupo: 'pessoa' },
    { id: '669', level: 4, label: 'S. Remígio', grupo: 'pessoa' },
    { id: '670', level: 4, label: 'Plácido e Companheiros', grupo: 'pessoa' },
    { id: '671', level: 4, label: 'S. Bruno', grupo: 'pessoa' },
    { id: '672', level: 4, label: 'Sta. Brígida', grupo: 'pessoa' },
    { id: '676', level: 4, label: 'S. Eduardo', grupo: 'pessoa' },
    { id: '678', level: 4, label: 'Sta. Edwiges', grupo: 'pessoa' },
    { id: '682', level: 4, label: 'S. João Câncio', grupo: 'pessoa' },
    { id: '689', level: 4, label: 'S. Leonardo de Limousin', grupo: 'pessoa' },
    { id: '694', level: 4, label: 'S. Martinho I', grupo: 'pessoa' },
    { id: '695', level: 4, label: 'S. Diogo', grupo: 'pessoa' },
    { id: '697', level: 4, label: 'Sto. Alberto Magno', grupo: 'pessoa' },
    { id: '698', level: 4, label: 'Sta. Gertrudes', grupo: 'pessoa' },
    { id: '700', level: 4, label: 'S. Félix de Valois', grupo: 'pessoa' },
    { id: '706', level: 4, label: 'S. Silvestre (Abade)', grupo: 'pessoa' },
    { id: '711', level: 4, label: 'S. Sabas', grupo: 'pessoa' },
    { id: '717', level: 4, label: 'S. Eusébio', grupo: 'pessoa' },
    { id: '719', level: 4, label: 'S. Tomás Becket', grupo: 'pessoa' },

    // ========== NÍVEL 5: ERA MODERNA (Séc XVI a XVIII) (nós — linhas calculadas automaticamente) ==========
    { id: '14', level: 5, label: 'Sto. Inácio de Loyola', grupo: 'pessoa' },
    { id: '15', level: 5, label: 'S. Francisco Xavier', grupo: 'pessoa' },
    { id: '12', level: 5, label: 'Sta. Teresa d\'Ávila', grupo: 'pessoa' },
    { id: '13', level: 5, label: 'S. João da Cruz', grupo: 'pessoa' },
    { id: '75', level: 5, label: 'S. Francisco de Sales', grupo: 'pessoa' },
    { id: '201', level: 5, label: 'Sto. Antônio Zaccaria', grupo: 'pessoa' },
    { id: '211', level: 5, label: 'S. Camilo de Léllis', grupo: 'pessoa' },
    { id: '212', level: 5, label: 'S. Vicente de Paulo', grupo: 'pessoa' },
    { id: '213', level: 5, label: 'S. Jerônimo Emiliani', grupo: 'pessoa' },
    { id: '235', level: 5, label: 'S. Luís Gonzaga', grupo: 'pessoa' },
    { id: '433', level: 5, label: 'S. João de Deus', grupo: 'pessoa' },
    { id: '452', level: 5, label: 'S. Fidélis de Sigmaringa', grupo: 'pessoa' },
    { id: '455', level: 5, label: 'S. Pedro Canísio', grupo: 'pessoa' },
    { id: '456', level: 5, label: 'S. Paulo da Cruz', grupo: 'pessoa' },
    { id: '601', level: 5, label: 'S. Pio V', grupo: 'pessoa' },
    { id: '608', level: 5, label: 'S. Roberto Belarmino', grupo: 'pessoa' },
    { id: '610', level: 5, label: 'S. João Batista de La Salle', grupo: 'pessoa' },
    { id: '612', level: 5, label: 'S. Pascoal Bailão', grupo: 'pessoa' },
    { id: '619', level: 5, label: 'S. Felipe Néri', grupo: 'pessoa' },
    { id: '624', level: 5, label: 'Sta. Maria Madalena de Pazzi', grupo: 'pessoa' },
    { id: '629', level: 5, label: 'Sto. Afonso M. de Ligório', grupo: 'pessoa' },
    { id: '633', level: 5, label: 'S. Caetano', grupo: 'pessoa' },
    { id: '642', level: 5, label: 'S. João Eudes', grupo: 'pessoa' },
    { id: '643', level: 5, label: 'Sta. Joana Francisca de Chantal', grupo: 'pessoa' },
    { id: '648', level: 5, label: 'S. José de Calasanz', grupo: 'pessoa' },
    { id: '649', level: 5, label: 'Sta. Rosa de Lima', grupo: 'pessoa' },
    { id: '659', level: 5, label: 'S. José de Cupertino', grupo: 'pessoa' },
    { id: '662', level: 5, label: 'S. Tomás de Vilanova', grupo: 'pessoa' },
    { id: '673', level: 5, label: 'S. João Leonardo', grupo: 'pessoa' },
    { id: '675', level: 5, label: 'S. Francisco de Borja', grupo: 'pessoa' },
    { id: '679', level: 5, label: 'Sta. Margarida Maria Alacoque', grupo: 'pessoa' },
    { id: '681', level: 5, label: 'S. Pedro de Alcântara', grupo: 'pessoa' },
    { id: '688', level: 5, label: 'S. Carlos Borromeu', grupo: 'pessoa' },
    { id: '692', level: 5, label: 'Sto. André Avelino', grupo: 'pessoa' },
    { id: '696', level: 5, label: 'S. Josafá', grupo: 'pessoa' },

    // ========== NÍVEL 6: CONTEMPORÂNEA (Fátima inclusa, 5 nós) ==========
    { id: '16', level: 6, label: 'S. João M. Vianney', grupo: 'pessoa' },
    { id: '61', level: 6, label: 'S. João Bosco', grupo: 'pessoa' },
    { id: '17', level: 6, label: 'Sta. Teresinha', grupo: 'pessoa' },
    { id: '19', level: 6, label: 'S. Pio X', grupo: 'pessoa' },
    { id: '429', level: 6, label: 'S. Gabriel da V. Dolorosa', grupo: 'pessoa' },
    { id: '609', level: 6, label: 'N. Sra. do Rosário de Fátima', grupo: 'pessoa' },

    // ========== NÍVEL 7: CONGREGAÇÕES E OBRAS ==========
    { id: '22', level: 7, categoria: 'fundadora', label: 'Ordem Beneditina', grupo: 'instituicao', font: { bold: true } },
    { id: '23', level: 7, categoria: 'fundadora', label: 'Ordem Franciscana', grupo: 'instituicao', font: { bold: true } },
    { id: '24', level: 7, categoria: 'fundadora', label: 'Ordem Dominicana', grupo: 'instituicao', font: { bold: true } },
    { id: '25', level: 7, categoria: 'fundadora', label: 'Companhia de Jesus', grupo: 'instituicao', font: { bold: true } },
    { id: '62', level: 7, categoria: 'fundadora', label: 'Família Salesiana', grupo: 'instituicao', font: { bold: true } },
    { id: '32', level: 7, categoria: 'fundadora', label: 'Suma Teológica', grupo: 'documento', font: { size: 12 } },
    { id: '34', level: 7, categoria: 'fundadora', label: 'Exercícios Espirituais', grupo: 'documento', font: { size: 12 } },
    { id: '38', level: 7, categoria: 'fundadora', label: 'Mística Cristã', grupo: 'ideia', font: { size: 12 } },
    { id: '63', level: 7, categoria: 'reformada', label: 'Ordem Cisterciense', grupo: 'instituicao', font: { bold: true } },
    { id: '41', level: 7, categoria: 'reformada', label: 'Carmelo Descalço', grupo: 'instituicao', font: { bold: true } },

// ========== NÍVEL 8: GEOGRAFIA (Atuação/Nascimento) — linhas calculadas automaticamente ==========
    { id: '130', level: 8, categoria: 'atuacao', label: 'Nazaré', grupo: 'localizacao' },
    { id: '131', level: 8, categoria: 'atuacao', label: 'Rio Jordão', grupo: 'localizacao' },
    { id: '132', level: 8, categoria: 'atuacao', label: 'Éfeso', grupo: 'localizacao' },
    { id: '134', level: 8, categoria: 'atuacao', label: 'Lida', grupo: 'localizacao' },
    { id: '135', level: 8, categoria: 'atuacao', label: 'Tebaida', grupo: 'localizacao' },
    { id: '137', level: 8, categoria: 'atuacao', label: 'Hipona', grupo: 'localizacao' },
    { id: '138', level: 8, categoria: 'atuacao', label: 'Antioquia', grupo: 'localizacao' },
    { id: '141', level: 8, categoria: 'atuacao', label: 'Monte Cassino', grupo: 'localizacao' },
    { id: '142', level: 8, categoria: 'atuacao', label: 'Claraval', grupo: 'localizacao' },
    { id: '143', level: 8, categoria: 'atuacao', label: 'Assis', grupo: 'localizacao' },
    { id: '147', level: 8, categoria: 'atuacao', label: 'Cássia', grupo: 'localizacao' },
    { id: '148', level: 8, categoria: 'atuacao', label: 'Goa', grupo: 'localizacao' },
    { id: '149', level: 8, categoria: 'atuacao', label: 'Ávila', grupo: 'localizacao' },
    { id: '151', level: 8, categoria: 'atuacao', label: 'Genebra', grupo: 'localizacao' },
    { id: '152', level: 8, categoria: 'atuacao', label: 'Ars', grupo: 'localizacao' },
    { id: '153', level: 8, categoria: 'atuacao', label: 'Turim', grupo: 'localizacao' },
    { id: '154', level: 8, categoria: 'atuacao', label: 'Lisieux', grupo: 'localizacao' },
    { id: '159', level: 8, categoria: 'atuacao', label: 'Querala', grupo: 'localizacao' },
    { id: '160', level: 8, categoria: 'atuacao', label: 'Etiópia', grupo: 'localizacao' },
    { id: '300', level: 8, categoria: 'atuacao', label: 'Milão', grupo: 'localizacao' },
    { id: '301', level: 8, categoria: 'atuacao', label: 'Morávia', grupo: 'localizacao' },
    { id: '302', level: 8, categoria: 'atuacao', label: 'Coimbra', grupo: 'localizacao' },
    { id: '303', level: 8, categoria: 'atuacao', label: 'Vallombrosa', grupo: 'localizacao' },
    { id: '304', level: 8, categoria: 'atuacao', label: 'Lyon', grupo: 'localizacao' },
    { id: '305', level: 8, categoria: 'atuacao', label: 'Bamberg', grupo: 'localizacao' },
    { id: '306', level: 8, categoria: 'atuacao', label: 'Somasca', grupo: 'localizacao' },
    { id: '309', level: 8, categoria: 'atuacao', label: 'Betânia', grupo: 'localizacao' },
    { id: '311', level: 8, categoria: 'atuacao', label: 'Maguncia', grupo: 'localizacao' },
    { id: '312', level: 8, categoria: 'atuacao', label: 'Magdeburgo', grupo: 'localizacao' },
    { id: '313', level: 8, categoria: 'atuacao', label: 'Edimburgo', grupo: 'localizacao' },
    { id: '315', level: 8, categoria: 'atuacao', label: 'Cesareia', grupo: 'localizacao' },
    { id: '316', level: 8, categoria: 'atuacao', label: 'Edessa', grupo: 'localizacao' },
    { id: '317', level: 8, categoria: 'atuacao', label: 'Florença', grupo: 'localizacao' },
    { id: '318', level: 8, categoria: 'atuacao', label: 'Nola', grupo: 'localizacao' },
    { id: '319', level: 8, categoria: 'atuacao', label: 'Monte Vergine', grupo: 'localizacao' },
    { id: '500', level: 8, categoria: 'atuacao', label: 'Poitiers', grupo: 'localizacao' },
    { id: '501', level: 8, categoria: 'atuacao', label: 'Glanfeuil', grupo: 'localizacao' },
    { id: '502', level: 8, categoria: 'atuacao', label: 'Odense', grupo: 'localizacao' },
    { id: '503', level: 8, categoria: 'atuacao', label: 'Saragoça', grupo: 'localizacao' },
    { id: '504', level: 8, categoria: 'atuacao', label: 'Barcelona', grupo: 'localizacao' },
    { id: '505', level: 8, categoria: 'atuacao', label: 'Esmirna', grupo: 'localizacao' },
    { id: '506', level: 8, categoria: 'atuacao', label: 'Constantinopla', grupo: 'localizacao' },
    { id: '507', level: 8, categoria: 'atuacao', label: 'Fiesole', grupo: 'localizacao' },
    { id: '508', level: 8, categoria: 'atuacao', label: 'Creta', grupo: 'localizacao' },
    { id: '509', level: 8, categoria: 'atuacao', label: 'Camaldoli', grupo: 'localizacao' },
    { id: '510', level: 8, categoria: 'atuacao', label: 'Alexandria', grupo: 'localizacao' },
    { id: '511', level: 8, categoria: 'atuacao', label: 'Lourdes', grupo: 'localizacao' },
    { id: '512', level: 8, categoria: 'atuacao', label: 'Bréscia', grupo: 'localizacao' },
    { id: '513', level: 8, categoria: 'atuacao', label: 'Fonte Avellana', grupo: 'localizacao' },
    { id: '514', level: 8, categoria: 'atuacao', label: 'Isola Gran Sasso', grupo: 'localizacao' },
    { id: '515', level: 8, categoria: 'atuacao', label: 'Cracóvia', grupo: 'localizacao' },
    { id: '517', level: 8, categoria: 'atuacao', label: 'Granada', grupo: 'localizacao' },
    { id: '518', level: 8, categoria: 'atuacao', label: 'Irlanda', grupo: 'localizacao' },
    { id: '519', level: 8, categoria: 'atuacao', label: 'Damasco', grupo: 'localizacao' },
    { id: '520', level: 8, categoria: 'atuacao', label: 'Sevilha', grupo: 'localizacao' },
    { id: '521', level: 8, categoria: 'atuacao', label: 'Valência', grupo: 'localizacao' },
    { id: '522', level: 8, categoria: 'atuacao', label: 'Tarragona', grupo: 'localizacao' },
    { id: '523', level: 8, categoria: 'atuacao', label: 'Cantuária', grupo: 'localizacao' },
    { id: '524', level: 8, categoria: 'atuacao', label: 'Seewis', grupo: 'localizacao' },
    { id: '525', level: 8, categoria: 'atuacao', label: 'Veneza', grupo: 'localizacao' },
    { id: '526', level: 8, categoria: 'atuacao', label: 'Friburgo', grupo: 'localizacao' },
    { id: '527', level: 8, categoria: 'atuacao', label: 'Siena', grupo: 'localizacao' },
    { id: '801', level: 8, categoria: 'atuacao', label: 'Fátima', grupo: 'localizacao' },

    // ========== NÍVEL 8: GEOGRAFIA (Martírio/Morte) — linhas calculadas automaticamente ==========
    { id: '26',  level: 8, categoria: 'morte', label: 'Roma', grupo: 'localizacao', font: { bold: true } },
    { id: '133', level: 8, categoria: 'morte', label: 'Jerusalém', grupo: 'localizacao', font: { bold: true } },
    { id: '136', level: 8, categoria: 'morte', label: 'Óstia', grupo: 'localizacao' },
    { id: '139', level: 8, categoria: 'morte', label: 'Sebaste', grupo: 'localizacao' },
    { id: '140', level: 8, categoria: 'morte', label: 'Catânia', grupo: 'localizacao' },
    { id: '144', level: 8, categoria: 'morte', label: 'Bolonha', grupo: 'localizacao' },
    { id: '145', level: 8, categoria: 'morte', label: 'Nápoles', grupo: 'localizacao' },
    { id: '146', level: 8, categoria: 'morte', label: 'Pádua', grupo: 'localizacao' },
    { id: '150', level: 8, categoria: 'morte', label: 'Úbeda', grupo: 'localizacao' },
    { id: '155', level: 8, categoria: 'morte', label: 'Patras', grupo: 'localizacao' },
    { id: '156', level: 8, categoria: 'morte', label: 'Santiago (Compostela)', grupo: 'localizacao' },
    { id: '157', level: 8, categoria: 'morte', label: 'Hierápolis', grupo: 'localizacao' },
    { id: '158', level: 8, categoria: 'morte', label: 'Armênia', grupo: 'localizacao' },
    { id: '161', level: 8, categoria: 'morte', label: 'Pérsia', grupo: 'localizacao' },
    { id: '307', level: 8, categoria: 'morte', label: 'Bolsena', grupo: 'localizacao' },
    { id: '308', level: 8, categoria: 'morte', label: 'Nicomédia', grupo: 'localizacao' },
    { id: '310', level: 8, categoria: 'morte', label: 'Ravena', grupo: 'localizacao' },
    { id: '314', level: 8, categoria: 'morte', label: 'Chipre', grupo: 'localizacao' },
    { id: '320', level: 8, categoria: 'morte', label: 'Paris', grupo: 'localizacao' },
    { id: '516', level: 8, categoria: 'morte', label: 'Cartago', grupo: 'localizacao' },
    { id: '800', level: 8, categoria: 'morte', label: 'Tours', grupo: 'localizacao' }
];

var todosSetas = [
    // ATRIBUTOS -> SANTOS (Nível 1 descendo)
    // Papas (56)
    { from: '56', to: '2', title: 'título de', texto: 'título de' },
    { from: '56', to: '19', title: 'título de', texto: 'título de' },
    { from: '56', to: '200', title: 'título de', texto: 'título de' },
    { from: '56', to: '205', title: 'título de', texto: 'título de' },
    { from: '56', to: '207', title: 'título de', texto: 'título de' },
    { from: '56', to: '234', title: 'título de', texto: 'título de' },
    { from: '56', to: '400', title: 'título de', texto: 'título de' },
    { from: '56', to: '404', title: 'título de', texto: 'título de' },
    { from: '56', to: '408', title: 'título de', texto: 'título de' },
    { from: '56', to: '431', title: 'título de', texto: 'título de' },
    { from: '56', to: '436', title: 'título de', texto: 'título de' },
    { from: '56', to: '445', title: 'título de', texto: 'título de' },
    { from: '56', to: '449', title: 'título de', texto: 'título de' },
    { from: '56', to: '451', title: 'título de', texto: 'título de' },
    { from: '56', to: '454', title: 'título de', texto: 'título de' },
    { from: '56', to: '601', title: 'título de', texto: 'título de' },
    { from: '56', to: '614', title: 'título de', texto: 'título de' },
    { from: '56', to: '617', title: 'título de', texto: 'título de' },
    { from: '56', to: '618', title: 'título de', texto: 'título de' },
    { from: '56', to: '620', title: 'título de', texto: 'título de' },
    { from: '56', to: '622', title: 'título de', texto: 'título de' },
    { from: '56', to: '625', title: 'título de', texto: 'título de' },
    { from: '56', to: '647', title: 'título de', texto: 'título de' },
    { from: '56', to: '658', title: 'título de', texto: 'título de' },
    { from: '56', to: '664', title: 'título de', texto: 'título de' },
    { from: '56', to: '677', title: 'título de', texto: 'título de' },
    { from: '56', to: '687', title: 'título de', texto: 'título de' },
    { from: '56', to: '694', title: 'título de', texto: 'título de' },
    { from: '56', to: '702', title: 'título de', texto: 'título de' },
    { from: '56', to: '714', title: 'título de', texto: 'título de' },
    { from: '56', to: '715', title: 'título de', texto: 'título de' },
    { from: '56', to: '720', title: 'título de', texto: 'título de' },

    // Bispos (57)
    { from: '57', to: '5', title: 'título de', texto: 'título de' },
    { from: '57', to: '75', title: 'título de', texto: 'título de' },
    { from: '57', to: '81', title: 'título de', texto: 'título de' },
    { from: '57', to: '82', title: 'título de', texto: 'título de' },
    { from: '57', to: '208', title: 'título de', texto: 'título de' },
    { from: '57', to: '216', title: 'título de', texto: 'título de' },
    { from: '57', to: '224', title: 'título de', texto: 'título de' },
    { from: '57', to: '225', title: 'título de', texto: 'título de' },
    { from: '57', to: '229', title: 'título de', texto: 'título de' },
    { from: '57', to: '236', title: 'título de', texto: 'título de' },
    { from: '57', to: '239', title: 'título de', texto: 'título de' },
    { from: '57', to: '401', title: 'título de', texto: 'título de' },
    { from: '57', to: '412', title: 'título de', texto: 'título de' },
    { from: '57', to: '413', title: 'título de', texto: 'título de' },
    { from: '57', to: '414', title: 'título de', texto: 'título de' },
    { from: '57', to: '417', title: 'título de', texto: 'título de' },
    { from: '57', to: '418', title: 'título de', texto: 'título de' },
    { from: '57', to: '422', title: 'título de', texto: 'título de' },
    { from: '57', to: '427', title: 'título de', texto: 'título de' },
    { from: '57', to: '428', title: 'título de', texto: 'título de' },
    { from: '57', to: '437', title: 'título de', texto: 'título de' },
    { from: '57', to: '438', title: 'título de', texto: 'título de' },
    { from: '57', to: '443', title: 'título de', texto: 'título de' },
    { from: '57', to: '450', title: 'título de', texto: 'título de' },
    { from: '57', to: '55', title: 'título de', texto: 'título de' },
    { from: '57', to: '600', title: 'título de', texto: 'título de' },
    { from: '57', to: '602', title: 'título de', texto: 'título de' },
    { from: '57', to: '604', title: 'título de', texto: 'título de' },
    { from: '57', to: '605', title: 'título de', texto: 'título de' },
    { from: '57', to: '608', title: 'título de', texto: 'título de' },
    { from: '57', to: '611', title: 'título de', texto: 'título de' },
    { from: '57', to: '623', title: 'título de', texto: 'título de' },
    { from: '57', to: '629', title: 'título de', texto: 'título de' },
    { from: '57', to: '654', title: 'título de', texto: 'título de' },
    { from: '57', to: '660', title: 'título de', texto: 'título de' },
    { from: '57', to: '662', title: 'título de', texto: 'título de' },
    { from: '57', to: '669', title: 'título de', texto: 'título de' },
    { from: '57', to: '688', title: 'título de', texto: 'título de' },
    { from: '57', to: '693', title: 'título de', texto: 'título de' },
    { from: '57', to: '696', title: 'título de', texto: 'título de' },
    { from: '57', to: '697', title: 'título de', texto: 'título de' },
    { from: '57', to: '699', title: 'título de', texto: 'título de' },
    { from: '57', to: '707', title: 'título de', texto: 'título de' },
    { from: '57', to: '710', title: 'título de', texto: 'título de' },
    { from: '57', to: '712', title: 'título de', texto: 'título de' },
    { from: '57', to: '713', title: 'título de', texto: 'título de' },
    { from: '57', to: '717', title: 'título de', texto: 'título de' },
    { from: '57', to: '719', title: 'título de', texto: 'título de' },

    // Abades (59)
    { from: '59', to: '74', title: 'título de', texto: 'título de' },
    { from: '59', to: '6', title: 'título de', texto: 'título de' },
    { from: '59', to: '66', title: 'título de', texto: 'título de' },
    { from: '59', to: '206', title: 'título de', texto: 'título de' },
    { from: '59', to: '238', title: 'título de', texto: 'título de' },
    { from: '59', to: '403', title: 'título de', texto: 'título de' },
    { from: '59', to: '420', title: 'título de', texto: 'título de' },
    { from: '59', to: '651', title: 'título de', texto: 'título de' },
    { from: '59', to: '683', title: 'título de', texto: 'título de' },
    { from: '59', to: '706', title: 'título de', texto: 'título de' },
    { from: '59', to: '711', title: 'título de', texto: 'título de' },

    // Viúvas (60)
    { from: '60', to: '64', title: 'título de', texto: 'título de' },
    { from: '60', to: '67', title: 'título de', texto: 'título de' },
    { from: '60', to: '203', title: 'título de', texto: 'título de' },
    { from: '60', to: '227', title: 'título de', texto: 'título de' },
    { from: '60', to: '218', title: 'título de', texto: 'título de' },
    { from: '60', to: '434', title: 'título de', texto: 'título de' },
    { from: '60', to: '643', title: 'título de', texto: 'título de' },
    { from: '60', to: '672', title: 'título de', texto: 'título de' },
    { from: '60', to: '678', title: 'título de', texto: 'título de' },

    // Virgens (52)
    { from: '52', to: '73', title: 'título de', texto: 'título de' },
    { from: '52', to: '11', title: 'título de', texto: 'título de' },
    { from: '52', to: '12', title: 'título de', texto: 'título de' },
    { from: '52', to: '17', title: 'título de', texto: 'título de' },
    { from: '52', to: '83', title: 'título de', texto: 'título de' },
    { from: '52', to: '85', title: 'título de', texto: 'título de' },
    { from: '52', to: '214', title: 'título de', texto: 'título de' },
    { from: '52', to: '217', title: 'título de', texto: 'título de' },
    { from: '52', to: '232', title: 'título de', texto: 'título de' },
    { from: '52', to: '221', title: 'título de', texto: 'título de' },
    { from: '52', to: '405', title: 'título de', texto: 'título de' },
    { from: '52', to: '411', title: 'título de', texto: 'título de' },
    { from: '52', to: '416', title: 'título de', texto: 'título de' },
    { from: '52', to: '419', title: 'título de', texto: 'título de' },
    { from: '52', to: '423', title: 'título de', texto: 'título de' },
    { from: '52', to: '424', title: 'título de', texto: 'título de' },
    { from: '52', to: '440', title: 'título de', texto: 'título de' },
    { from: '52', to: '441', title: 'título de', texto: 'título de' },
    { from: '52', to: '459', title: 'título de', texto: 'título de' },
    { from: '52', to: '615', title: 'título de', texto: 'título de' },
    { from: '52', to: '624', title: 'título de', texto: 'título de' },
    { from: '52', to: '626', title: 'título de', texto: 'título de' },
    { from: '52', to: '628', title: 'título de', texto: 'título de' },
    { from: '52', to: '649', title: 'título de', texto: 'título de' },
    { from: '52', to: '679', title: 'título de', texto: 'título de' },
    { from: '52', to: '684', title: 'título de', texto: 'título de' },
    { from: '52', to: '698', title: 'título de', texto: 'título de' },
    { from: '52', to: '701', title: 'título de', texto: 'título de' },
    { from: '52', to: '705', title: 'título de', texto: 'título de' },
    { from: '52', to: '709', title: 'título de', texto: 'título de' },
    { from: '52', to: '716', title: 'título de', texto: 'título de' },

    // Penitentes (54)
    { from: '54', to: '215', title: 'título de', texto: 'título de' },

    // Doutores (51)
    { from: '51', to: '5', title: 'título de', texto: 'título de' },
    { from: '51', to: '10', title: 'título de', texto: 'título de' },
    { from: '51', to: '13', title: 'título de', texto: 'título de' },
    { from: '51', to: '65', title: 'título de', texto: 'título de' },
    { from: '51', to: '66', title: 'título de', texto: 'título de' },
    { from: '51', to: '75', title: 'título de', texto: 'título de' },
    { from: '51', to: '208', title: 'título de', texto: 'título de' },
    { from: '51', to: '229', title: 'título de', texto: 'título de' },
    { from: '51', to: '231', title: 'título de', texto: 'título de' },
    { from: '51', to: '401', title: 'título de', texto: 'título de' },
    { from: '51', to: '414', title: 'título de', texto: 'título de' },
    { from: '51', to: '422', title: 'título de', texto: 'título de' },
    { from: '51', to: '428', title: 'título de', texto: 'título de' },
    { from: '51', to: '436', title: 'título de', texto: 'título de' },
    { from: '51', to: '438', title: 'título de', texto: 'título de' },
    { from: '51', to: '442', title: 'título de', texto: 'título de' },
    { from: '51', to: '443', title: 'título de', texto: 'título de' },
    { from: '51', to: '445', title: 'título de', texto: 'título de' },
    { from: '51', to: '450', title: 'título de', texto: 'título de' },
    { from: '51', to: '455', title: 'título de', texto: 'título de' },
    { from: '51', to: '600', title: 'título de', texto: 'título de' },
    { from: '51', to: '604', title: 'título de', texto: 'título de' },
    { from: '51', to: '608', title: 'título de', texto: 'título de' },
    { from: '51', to: '621', title: 'título de', texto: 'título de' },
    { from: '51', to: '629', title: 'título de', texto: 'título de' },
    { from: '51', to: '668', title: 'título de', texto: 'título de' },
    { from: '51', to: '697', title: 'título de', texto: 'título de' },
    { from: '51', to: '710', title: 'título de', texto: 'título de' },
    { from: '51', to: '713', title: 'título de', texto: 'título de' },

    // Mártires (50)
    { from: '50', to: '71', title: 'título de', texto: 'título de' },
    { from: '50', to: '2', title: 'título de', texto: 'título de' },
    { from: '50', to: '3', title: 'título de', texto: 'título de' },
    { from: '50', to: '73', title: 'título de', texto: 'título de' },
    { from: '50', to: '72', title: 'título de', texto: 'título de' },
    { from: '50', to: '7', title: 'título de', texto: 'título de' },
    { from: '50', to: '86', title: 'título de', texto: 'título de' },
    { from: '50', to: '81', title: 'título de', texto: 'título de' },
    { from: '50', to: '82', title: 'título de', texto: 'título de' },
    { from: '50', to: '83', title: 'título de', texto: 'título de' },
    { from: '50', to: '84', title: 'título de', texto: 'título de' },
    { from: '50', to: '110', title: 'título de', texto: 'título de' },
    { from: '50', to: '111', title: 'título de', texto: 'título de' },
    { from: '50', to: '112', title: 'título de', texto: 'título de' },
    { from: '50', to: '113', title: 'título de', texto: 'título de' },
    { from: '50', to: '114', title: 'título de', texto: 'título de' },
    { from: '50', to: '115', title: 'título de', texto: 'título de' },
    { from: '50', to: '116', title: 'título de', texto: 'título de' },
    { from: '50', to: '117', title: 'título de', texto: 'título de' },
    { from: '50', to: '118', title: 'título de', texto: 'título de' },
    { from: '50', to: '228', title: 'título de', texto: 'título de' },
    { from: '50', to: '204', title: 'título de', texto: 'título de' },
    { from: '50', to: '205', title: 'título de', texto: 'título de' },
    { from: '50', to: '207', title: 'título de', texto: 'título de' },
    { from: '50', to: '216', title: 'título de', texto: 'título de' },
    { from: '50', to: '217', title: 'título de', texto: 'título de' },
    { from: '50', to: '219', title: 'título de', texto: 'título de' },
    { from: '50', to: '220', title: 'título de', texto: 'título de' },
    { from: '50', to: '222', title: 'título de', texto: 'título de' },
    { from: '50', to: '223', title: 'título de', texto: 'título de' },
    { from: '50', to: '224', title: 'título de', texto: 'título de' },
    { from: '50', to: '226', title: 'título de', texto: 'título de' },
    { from: '50', to: '230', title: 'título de', texto: 'título de' },
    { from: '50', to: '233', title: 'título de', texto: 'título de' },
    { from: '50', to: '234', title: 'título de', texto: 'título de' },
    { from: '50', to: '237', title: 'título de', texto: 'título de' },
    { from: '50', to: '239', title: 'título de', texto: 'título de' },
    { from: '50', to: '400', title: 'título de', texto: 'título de' },
    { from: '50', to: '402', title: 'título de', texto: 'título de' },
    { from: '50', to: '404', title: 'título de', texto: 'título de' },
    { from: '50', to: '405', title: 'título de', texto: 'título de' },
    { from: '50', to: '406', title: 'título de', texto: 'título de' },
    { from: '50', to: '407', title: 'título de', texto: 'título de' },
    { from: '50', to: '408', title: 'título de', texto: 'título de' },
    { from: '50', to: '409', title: 'título de', texto: 'título de' },
    { from: '50', to: '411', title: 'título de', texto: 'título de' },
    { from: '50', to: '412', title: 'título de', texto: 'título de' },
    { from: '50', to: '413', title: 'título de', texto: 'título de' },
    { from: '50', to: '416', title: 'título de', texto: 'título de' },
    { from: '50', to: '419', title: 'título de', texto: 'título de' },
    { from: '50', to: '423', title: 'título de', texto: 'título de' },
    { from: '50', to: '426', title: 'título de', texto: 'título de' },
    { from: '50', to: '427', title: 'título de', texto: 'título de' },
    { from: '50', to: '431', title: 'título de', texto: 'título de' },
    { from: '50', to: '432', title: 'título de', texto: 'título de' },
    { from: '50', to: '435', title: 'título de', texto: 'título de' },
    { from: '50', to: '446', title: 'título de', texto: 'título de' },
    { from: '50', to: '447', title: 'título de', texto: 'título de' },
    { from: '50', to: '448', title: 'título de', texto: 'título de' },
    { from: '50', to: '449', title: 'título de', texto: 'título de' },
    { from: '50', to: '451', title: 'título de', texto: 'título de' },
    { from: '50', to: '452', title: 'título de', texto: 'título de' },
    { from: '50', to: '453', title: 'título de', texto: 'título de' },
    { from: '50', to: '454', title: 'título de', texto: 'título de' },
    { from: '50', to: '457', title: 'título de', texto: 'título de' },
    { from: '50', to: '458', title: 'título de', texto: 'título de' },
    { from: '50', to: '602', title: 'título de', texto: 'título de' },
    { from: '50', to: '606', title: 'título de', texto: 'título de' },
    { from: '50', to: '607', title: 'título de', texto: 'título de' },
    { from: '50', to: '613', title: 'título de', texto: 'título de' },
    { from: '50', to: '618', title: 'título de', texto: 'título de' },
    { from: '50', to: '620', title: 'título de', texto: 'título de' },
    { from: '50', to: '622', title: 'título de', texto: 'título de' },
    { from: '50', to: '625', title: 'título de', texto: 'título de' },
    { from: '50', to: '630', title: 'título de', texto: 'título de' },
    { from: '50', to: '634', title: 'título de', texto: 'título de' },
    { from: '50', to: '635', title: 'título de', texto: 'título de' },
    { from: '50', to: '636', title: 'título de', texto: 'título de' },
    { from: '50', to: '637', title: 'título de', texto: 'título de' },
    { from: '50', to: '641', title: 'título de', texto: 'título de' },
    { from: '50', to: '647', title: 'título de', texto: 'título de' },
    { from: '50', to: '652', title: 'título de', texto: 'título de' },
    { from: '50', to: '655', title: 'título de', texto: 'título de' },
    { from: '50', to: '657', title: 'título de', texto: 'título de' },
    { from: '50', to: '658', title: 'título de', texto: 'título de' },
    { from: '50', to: '660', title: 'título de', texto: 'título de' },
    { from: '50', to: '661', title: 'título de', texto: 'título de' },
    { from: '50', to: '663', title: 'título de', texto: 'título de' },
    { from: '50', to: '664', title: 'título de', texto: 'título de' },
    { from: '50', to: '665', title: 'título de', texto: 'título de' },
    { from: '50', to: '666', title: 'título de', texto: 'título de' },
    { from: '50', to: '667', title: 'título de', texto: 'título de' },
    { from: '50', to: '670', title: 'título de', texto: 'título de' },
    { from: '50', to: '674', title: 'título de', texto: 'título de' },
    { from: '50', to: '677', title: 'título de', texto: 'título de' },
    { from: '50', to: '684', title: 'título de', texto: 'título de' },
    { from: '50', to: '686', title: 'título de', texto: 'título de' },
    { from: '50', to: '687', title: 'título de', texto: 'título de' },
    { from: '50', to: '690', title: 'título de', texto: 'título de' },
    { from: '50', to: '691', title: 'título de', texto: 'título de' },
    { from: '50', to: '694', title: 'título de', texto: 'título de' },
    { from: '50', to: '696', title: 'título de', texto: 'título de' },
    { from: '50', to: '701', title: 'título de', texto: 'título de' },
    { from: '50', to: '702', title: 'título de', texto: 'título de' },
    { from: '50', to: '703', title: 'título de', texto: 'título de' },
    { from: '50', to: '704', title: 'título de', texto: 'título de' },
    { from: '50', to: '705', title: 'título de', texto: 'título de' },
    { from: '50', to: '707', title: 'título de', texto: 'título de' },
    { from: '50', to: '708', title: 'título de', texto: 'título de' },
    { from: '50', to: '709', title: 'título de', texto: 'título de' },
    { from: '50', to: '714', title: 'título de', texto: 'título de' },
    { from: '50', to: '716', title: 'título de', texto: 'título de' },
    { from: '50', to: '717', title: 'título de', texto: 'título de' },
    { from: '50', to: '718', title: 'título de', texto: 'título de' },
    { from: '50', to: '719', title: 'título de', texto: 'título de' },

    // Confessores (53)
    { from: '53', to: '4', title: 'título de', texto: 'título de' },
    { from: '53', to: '76', title: 'título de', texto: 'título de' },
    { from: '53', to: '8', title: 'título de', texto: 'título de' },
    { from: '53', to: '9', title: 'título de', texto: 'título de' },
    { from: '53', to: '14', title: 'título de', texto: 'título de' },
    { from: '53', to: '15', title: 'título de', texto: 'título de' },
    { from: '53', to: '16', title: 'título de', texto: 'título de' },
    { from: '53', to: '61', title: 'título de', texto: 'título de' },
    { from: '53', to: '201', title: 'título de', texto: 'título de' },
    { from: '53', to: '202', title: 'título de', texto: 'título de' },
    { from: '53', to: '209', title: 'título de', texto: 'título de' },
    { from: '53', to: '210', title: 'título de', texto: 'título de' },
    { from: '53', to: '211', title: 'título de', texto: 'título de' },
    { from: '53', to: '212', title: 'título de', texto: 'título de' },
    { from: '53', to: '213', title: 'título de', texto: 'título de' },
    { from: '53', to: '235', title: 'título de', texto: 'título de' },
    { from: '53', to: '55', title: 'título de', texto: 'título de' },
    { from: '53', to: '410', title: 'título de', texto: 'título de' },
    { from: '53', to: '415', title: 'título de', texto: 'título de' },
    { from: '53', to: '421', title: 'título de', texto: 'título de' },
    { from: '53', to: '425', title: 'título de', texto: 'título de' },
    { from: '53', to: '429', title: 'título de', texto: 'título de' },
    { from: '53', to: '430', title: 'título de', texto: 'título de' },
    { from: '53', to: '433', title: 'título de', texto: 'título de' },
    { from: '53', to: '439', title: 'título de', texto: 'título de' },
    { from: '53', to: '444', title: 'título de', texto: 'título de' },
    { from: '53', to: '456', title: 'título de', texto: 'título de' },
    { from: '53', to: '600', title: 'título de', texto: 'título de' },
    { from: '53', to: '601', title: 'título de', texto: 'título de' },
    { from: '53', to: '604', title: 'título de', texto: 'título de' },
    { from: '53', to: '605', title: 'título de', texto: 'título de' },
    { from: '53', to: '608', title: 'título de', texto: 'título de' },
    { from: '53', to: '610', title: 'título de', texto: 'título de' },
    { from: '53', to: '611', title: 'título de', texto: 'título de' },
    { from: '53', to: '612', title: 'título de', texto: 'título de' },
    { from: '53', to: '614', title: 'título de', texto: 'título de' },
    { from: '53', to: '616', title: 'título de', texto: 'título de' },
    { from: '53', to: '617', title: 'título de', texto: 'título de' },
    { from: '53', to: '619', title: 'título de', texto: 'título de' },
    { from: '53', to: '621', title: 'título de', texto: 'título de' },
    { from: '53', to: '623', title: 'título de', texto: 'título de' },
    { from: '53', to: '627', title: 'título de', texto: 'título de' },
    { from: '53', to: '629', title: 'título de', texto: 'título de' },
    { from: '53', to: '633', title: 'título de', texto: 'título de' },
    { from: '53', to: '639', title: 'título de', texto: 'título de' },
    { from: '53', to: '640', title: 'título de', texto: 'título de' },
    { from: '53', to: '642', title: 'título de', texto: 'título de' },
    { from: '53', to: '645', title: 'título de', texto: 'título de' },
    { from: '53', to: '646', title: 'título de', texto: 'título de' },
    { from: '53', to: '648', title: 'título de', texto: 'título de' },
    { from: '53', to: '650', title: 'título de', texto: 'título de' },
    { from: '53', to: '651', title: 'título de', texto: 'título de' },
    { from: '53', to: '653', title: 'título de', texto: 'título de' },
    { from: '53', to: '654', title: 'título de', texto: 'título de' },
    { from: '53', to: '656', title: 'título de', texto: 'título de' },
    { from: '53', to: '659', title: 'título de', texto: 'título de' },
    { from: '53', to: '662', title: 'título de', texto: 'título de' },
    { from: '53', to: '668', title: 'título de', texto: 'título de' },
    { from: '53', to: '669', title: 'título de', texto: 'título de' },
    { from: '53', to: '671', title: 'título de', texto: 'título de' },
    { from: '53', to: '673', title: 'título de', texto: 'título de' },
    { from: '53', to: '675', title: 'título de', texto: 'título de' },
    { from: '53', to: '676', title: 'título de', texto: 'título de' },
    { from: '53', to: '681', title: 'título de', texto: 'título de' },
    { from: '53', to: '682', title: 'título de', texto: 'título de' },
    { from: '53', to: '683', title: 'título de', texto: 'título de' },
    { from: '53', to: '688', title: 'título de', texto: 'título de' },
    { from: '53', to: '689', title: 'título de', texto: 'título de' },
    { from: '53', to: '692', title: 'título de', texto: 'título de' },
    { from: '53', to: '693', title: 'título de', texto: 'título de' },
    { from: '53', to: '695', title: 'título de', texto: 'título de' },
    { from: '53', to: '697', title: 'título de', texto: 'título de' },
    { from: '53', to: '699', title: 'título de', texto: 'título de' },
    { from: '53', to: '700', title: 'título de', texto: 'título de' },
    { from: '53', to: '706', title: 'título de', texto: 'título de' },
    { from: '53', to: '710', title: 'título de', texto: 'título de' },
    { from: '53', to: '711', title: 'título de', texto: 'título de' },
    { from: '53', to: '712', title: 'título de', texto: 'título de' },
    { from: '53', to: '713', title: 'título de', texto: 'título de' },
    { from: '53', to: '715', title: 'título de', texto: 'título de' },
    { from: '53', to: '720', title: 'título de', texto: 'título de' },

    // Festa/Arcanjo (58) — título novo, para nós que não se encaixam
    // nas categorias tradicionais (arcanjos, festas e mistérios marianos/
    // cristológicos). Exceção: 680 (S. Lucas Evangelista) é evangelista,
    // não arcanjo/festa — incluído aqui por decisão explícita, mas
    // conceitualmente destoa do grupo; revisar se fizer sentido depois.
    { from: '58', to: '603', title: 'título de', texto: 'título de' },
    { from: '58', to: '609', title: 'título de', texto: 'título de' },
    { from: '58', to: '631', title: 'título de', texto: 'título de' },
    { from: '58', to: '632', title: 'título de', texto: 'título de' },
    { from: '58', to: '638', title: 'título de', texto: 'título de' },
    { from: '58', to: '644', title: 'título de', texto: 'título de' },
    { from: '58', to: '680', title: 'título de', texto: 'título de' },
    { from: '58', to: '685', title: 'título de', texto: 'título de' },

    // ========== CALENDÁRIO -> SANTOS ==========
    // Janeiro (70)
    { from: '70', to: '400', texto: 'Dia 11' },
    { from: '70', to: '401', texto: 'Dia 14' },
    { from: '70', to: '402', texto: 'Dia 14' },
    { from: '70', to: '76',  texto: 'Dia 15' },
    { from: '70', to: '403', texto: 'Dia 15' },
    { from: '70', to: '404', texto: 'Dia 16' },
    { from: '70', to: '74',  texto: 'Dia 17' },
    { from: '70', to: '2',   texto: 'Cátedra Roma (18)' },
    { from: '70', to: '3',   texto: 'Dia 18' },
    { from: '70', to: '405', texto: 'Dia 18' },
    { from: '70', to: '406', texto: 'Dia 19' },
    { from: '70', to: '407', texto: 'Dia 19' },
    { from: '70', to: '408', texto: 'Dia 20' },
    { from: '70', to: '72',  texto: 'Dia 20' },
    { from: '70', to: '73',  texto: 'Dia 21' },
    { from: '70', to: '409', texto: 'Dia 22' },
    { from: '70', to: '410', texto: 'Dia 23' },
    { from: '70', to: '411', texto: 'Dia 23' },
    { from: '70', to: '412', texto: 'Dia 24' },
    { from: '70', to: '3',   texto: 'Conversão (25)' },
    { from: '70', to: '413', texto: 'Dia 26' },
    { from: '70', to: '414', texto: 'Dia 27' },
    { from: '70', to: '415', texto: 'Dia 28' },
    { from: '70', to: '73',  texto: 'Secundo (28)' },
    { from: '70', to: '75',  texto: 'Dia 29' },
    { from: '70', to: '416', texto: 'Dia 30' },
    { from: '70', to: '61',  texto: 'Dia 31' },

    // Fevereiro (80)
    { from: '80', to: '81',  texto: 'Dia 1' },
    { from: '80', to: '82',  texto: 'Dia 3' },
    { from: '80', to: '417', texto: 'Dia 4' },
    { from: '80', to: '83',  texto: 'Dia 5' },
    { from: '80', to: '418', texto: 'Dia 6' },
    { from: '80', to: '419', texto: 'Dia 6' },
    { from: '80', to: '420', texto: 'Dia 7' },
    { from: '80', to: '421', texto: 'Dia 8' },
    { from: '80', to: '422', texto: 'Dia 9' },
    { from: '80', to: '423', texto: 'Dia 9' },
    { from: '80', to: '85',  texto: 'Dia 10' },
    { from: '80', to: '424', texto: 'Dia 11' },
    { from: '80', to: '425', texto: 'Dia 12' },
    { from: '80', to: '84',  texto: 'Dia 14' },
    { from: '80', to: '426', texto: 'Dia 15' },
    { from: '80', to: '427', texto: 'Dia 18' },
    { from: '80', to: '2',   texto: 'Cátedra Antioquia (22)' },
    { from: '80', to: '428', texto: 'Dia 23' },
    { from: '80', to: '86',  texto: 'Dia 24 (ou 23)' },
    { from: '80', to: '429', texto: 'Dia 27' },

    // Março (90)
    { from: '90', to: '430', texto: 'Dia 4' },
    { from: '90', to: '431', texto: 'Dia 4' },
    { from: '90', to: '432', texto: 'Dia 6' },
    { from: '90', to: '10',  texto: 'Dia 7' },
    { from: '90', to: '433', texto: 'Dia 8' },
    { from: '90', to: '434', texto: 'Dia 9' },
    { from: '90', to: '435', texto: 'Dia 10' },
    { from: '90', to: '436', texto: 'Dia 12' },
    { from: '90', to: '437', texto: 'Dia 17' },
    { from: '90', to: '438', texto: 'Dia 18' },
    { from: '90', to: '4',   texto: 'Dia 19' },
    { from: '90', to: '6',   texto: 'Dia 21' },
    { from: '90', to: '439', texto: 'Dia 24' },
    { from: '90', to: '440', texto: 'Dia 25' },
    { from: '90', to: '441', texto: 'Dia 27' },
    { from: '90', to: '442', texto: 'Dia 27' },

    // Abril (91)
    { from: '91', to: '443', texto: 'Dia 4' },
    { from: '91', to: '444', texto: 'Dia 5' },
    { from: '91', to: '445', texto: 'Dia 11' },
    { from: '91', to: '446', texto: 'Dia 13' },
    { from: '91', to: '447', texto: 'Dia 14' },
    { from: '91', to: '448', texto: 'Dia 14' },
    { from: '91', to: '449', texto: 'Dia 17' },
    { from: '91', to: '450', texto: 'Dia 21' },
    { from: '91', to: '4',   texto: 'Dia 22' },
    { from: '91', to: '451', texto: 'Dia 22' },
    { from: '91', to: '7',   texto: 'Dia 23' },
    { from: '91', to: '452', texto: 'Dia 24' },
    { from: '91', to: '453', texto: 'Dia 25' },
    { from: '91', to: '454', texto: 'Dia 26' },
    { from: '91', to: '455', texto: 'Dia 27' },
    { from: '91', to: '456', texto: 'Dia 28' },
    { from: '91', to: '457', texto: 'Dia 28' },
    { from: '91', to: '458', texto: 'Dia 29' },
    { from: '91', to: '459', texto: 'Dia 30' },

    // Maio (92)
    { from: '92', to: '64',  texto: 'Dia 4' },
    { from: '92', to: '112', texto: 'Dia 11' },
    { from: '92', to: '116', texto: 'Dia 11' },
    { from: '92', to: '67',  texto: 'Dia 22' },
    { from: '92', to: '112', texto: 'Dia 1' },
    { from: '92', to: '116', texto: 'Dia 1' },
    { from: '92', to: '600', texto: 'Dia 2' },
    { from: '92', to: '601', texto: 'Dia 5' },
    { from: '92', to: '55', texto: 'Dia 6' },
    { from: '92', to: '602', texto: 'Dia 7' },
    { from: '92', to: '603', texto: 'Dia 8' },
    { from: '92', to: '604', texto: 'Dia 9' },
    { from: '92', to: '605', texto: 'Dia 10' },
    { from: '92', to: '606', texto: 'Dia 10' },
    { from: '92', to: '607', texto: 'Dia 12' },
    { from: '92', to: '608', texto: 'Dia 13' },
    { from: '92', to: '609', texto: 'Dia 13' },
    { from: '92', to: '224', texto: 'Dia 14' },
    { from: '92', to: '610', texto: 'Dia 15' },
    { from: '92', to: '611', texto: 'Dia 16' },
    { from: '92', to: '612', texto: 'Dia 17' },
    { from: '92', to: '613', texto: 'Dia 18' },
    { from: '92', to: '614', texto: 'Dia 19' },
    { from: '92', to: '615', texto: 'Dia 19' },
    { from: '92', to: '616', texto: 'Dia 20' },
    { from: '92', to: '617', texto: 'Dia 25' },
    { from: '92', to: '618', texto: 'Dia 25' },
    { from: '92', to: '619', texto: 'Dia 26' },
    { from: '92', to: '620', texto: 'Dia 26' },
    { from: '92', to: '621', texto: 'Dia 27' },
    { from: '92', to: '622', texto: 'Dia 27' },
    { from: '92', to: '623', texto: 'Dia 28' },
    { from: '92', to: '624', texto: 'Dia 29' },
    { from: '92', to: '625', texto: 'Dia 30' },
    { from: '92', to: '626', texto: 'Dia 30' },
    { from: '92', to: '627', texto: 'Dia 30' },
    { from: '92', to: '628', texto: 'Dia 31' },

    // Junho (93)
    { from: '93', to: '223', texto: 'Dia 2' },
    { from: '93', to: '224', texto: 'Dia 5' },
    { from: '93', to: '225', texto: 'Dia 6' },
    { from: '93', to: '226', texto: 'Dia 9' },
    { from: '93', to: '227', texto: 'Dia 10' },
    { from: '93', to: '228', texto: 'Dia 11' },
    { from: '93', to: '65',  texto: 'Dia 13' },
    { from: '93', to: '229', texto: 'Dia 14' },
    { from: '93', to: '230', texto: 'Dia 15' },
    { from: '93', to: '231', texto: 'Dia 18' },
    { from: '93', to: '232', texto: 'Dia 19' },
    { from: '93', to: '233', texto: 'Dia 19' },
    { from: '93', to: '234', texto: 'Dia 20' },
    { from: '93', to: '235', texto: 'Dia 21' },
    { from: '93', to: '236', texto: 'Dia 22' },
    { from: '93', to: '71',  texto: 'Dia 24' },
    { from: '93', to: '238', texto: 'Dia 25' },
    { from: '93', to: '237', texto: 'Dia 26' },
    { from: '93', to: '239', texto: 'Dia 28' },
    { from: '93', to: '2',   texto: 'Dia 29' },
    { from: '93', to: '3',   texto: 'Dia 29' },

    // Julho (94)
    { from: '94', to: '200', texto: 'Dia 3' },
    { from: '94', to: '201', texto: 'Dia 5' },
    { from: '94', to: '202', texto: 'Dia 7' },
    { from: '94', to: '203', texto: 'Dia 8' },
    { from: '94', to: '204', texto: 'Dia 10' },
    { from: '94', to: '205', texto: 'Dia 11' },
    { from: '94', to: '206', texto: 'Dia 12' },
    { from: '94', to: '207', texto: 'Dia 13' },
    { from: '94', to: '208', texto: 'Dia 14' },
    { from: '94', to: '209', texto: 'Dia 15' },
    { from: '94', to: '210', texto: 'Dia 17' },
    { from: '94', to: '211', texto: 'Dia 18' },
    { from: '94', to: '212', texto: 'Dia 19' },
    { from: '94', to: '213', texto: 'Dia 20' },
    { from: '94', to: '214', texto: 'Dia 21' },
    { from: '94', to: '215', texto: 'Dia 22' },
    { from: '94', to: '216', texto: 'Dia 23' },
    { from: '94', to: '217', texto: 'Dia 24' },
    { from: '94', to: '111', texto: 'Dia 25' },
    { from: '94', to: '218', texto: 'Dia 26' },
    { from: '94', to: '219', texto: 'Dia 27' },
    { from: '94', to: '220', texto: 'Dia 28' },
    { from: '94', to: '221', texto: 'Dia 29' },
    { from: '94', to: '222', texto: 'Dia 30' },
    { from: '94', to: '14',  texto: 'Dia 31' },

    // Agosto (95)
    { from: '95', to: '9',   texto: 'Dia 4' },
    { from: '95', to: '16',  texto: 'Dia 9' },
    { from: '95', to: '11',  texto: 'Dia 12' },
    { from: '95', to: '66',  texto: 'Dia 20' },
    { from: '95', to: '113', texto: 'Dia 24' },
    { from: '95', to: '5',   texto: 'Dia 28' },
    { from: '95', to: '2', texto: 'Dia 1 (Acorrentado)' },
    { from: '95', to: '629', texto: 'Dia 2' },
    { from: '95', to: '630', texto: 'Dia 3' },
    { from: '95', to: '631', texto: 'Dia 5' },
    { from: '95', to: '632', texto: 'Dia 6' },
    { from: '95', to: '633', texto: 'Dia 7' },
    { from: '95', to: '634', texto: 'Dia 8' },
    { from: '95', to: '635', texto: 'Dia 10' },
    { from: '95', to: '636', texto: 'Dia 11' },
    { from: '95', to: '637', texto: 'Dia 13' },
    { from: '95', to: '638', texto: 'Dia 15' },
    { from: '95', to: '639', texto: 'Dia 16' },
    { from: '95', to: '640', texto: 'Dia 17' },
    { from: '95', to: '641', texto: 'Dia 18' },
    { from: '95', to: '642', texto: 'Dia 19' },
    { from: '95', to: '643', texto: 'Dia 21' },
    { from: '95', to: '644', texto: 'Dia 22' },
    { from: '95', to: '645', texto: 'Dia 23' },
    { from: '95', to: '646', texto: 'Dia 25' },
    { from: '95', to: '647', texto: 'Dia 26' },
    { from: '95', to: '648', texto: 'Dia 27' },
    { from: '95', to: '71', texto: 'Dia 29' },
    { from: '95', to: '649', texto: 'Dia 30' },
    { from: '95', to: '650', texto: 'Dia 31' },

    // Setembro (96)
    { from: '96', to: '19',  texto: 'Dia 3' },
    { from: '96', to: '115', texto: 'Dia 21' },
    { from: '96', to: '651', texto: 'Dia 1' },
    { from: '96', to: '652', texto: 'Dia 1' },
    { from: '96', to: '653', texto: 'Dia 2' },
    { from: '96', to: '654', texto: 'Dia 5' },
    { from: '96', to: '655', texto: 'Dia 9' },
    { from: '96', to: '656', texto: 'Dia 10' },
    { from: '96', to: '657', texto: 'Dia 11' },
    { from: '96', to: '658', texto: 'Dia 16' },
    { from: '96', to: '8', texto: 'Dia 17' },
    { from: '96', to: '659', texto: 'Dia 18' },
    { from: '96', to: '660', texto: 'Dia 19' },
    { from: '96', to: '661', texto: 'Dia 20' },
    { from: '96', to: '662', texto: 'Dia 22' },
    { from: '96', to: '663', texto: 'Dia 22' },
    { from: '96', to: '664', texto: 'Dia 23' },
    { from: '96', to: '665', texto: 'Dia 26' },
    { from: '96', to: '666', texto: 'Dia 27' },
    { from: '96', to: '667', texto: 'Dia 28' },
    { from: '96', to: '603', texto: 'Dia 29' },
    { from: '96', to: '668', texto: 'Dia 30' },

    // Outubro (97)
    { from: '97', to: '17',  texto: 'Dia 3' },
    { from: '97', to: '8',   texto: 'Dia 4' },
    { from: '97', to: '12',  texto: 'Dia 15' },
    { from: '97', to: '117', texto: 'Dia 28' },
    { from: '97', to: '118', texto: 'Dia 28' },
    { from: '97', to: '669', texto: 'Dia 1' },
    { from: '97', to: '670', texto: 'Dia 5' },
    { from: '97', to: '671', texto: 'Dia 6' },
    { from: '97', to: '672', texto: 'Dia 8' },
    { from: '97', to: '673', texto: 'Dia 9' },
    { from: '97', to: '674', texto: 'Dia 9' },
    { from: '97', to: '675', texto: 'Dia 10' },
    { from: '97', to: '676', texto: 'Dia 13' },
    { from: '97', to: '677', texto: 'Dia 14' },
    { from: '97', to: '678', texto: 'Dia 16' },
    { from: '97', to: '679', texto: 'Dia 17' },
    { from: '97', to: '680', texto: 'Dia 18' },
    { from: '97', to: '681', texto: 'Dia 19' },
    { from: '97', to: '682', texto: 'Dia 20' },
    { from: '97', to: '683', texto: 'Dia 21' },
    { from: '97', to: '684', texto: 'Dia 21' },
    { from: '97', to: '685', texto: 'Dia 24' },
    { from: '97', to: '686', texto: 'Dia 25' },
    { from: '97', to: '687', texto: 'Dia 26' },

    // Novembro (98)
    { from: '98', to: '13',  texto: 'Dia 24' },
    { from: '98', to: '110', texto: 'Dia 30' },
    { from: '98', to: '688', texto: 'Dia 4' },
    { from: '98', to: '689', texto: 'Dia 6' },
    { from: '98', to: '690', texto: 'Dia 8' },
    { from: '98', to: '691', texto: 'Dia 9' },
    { from: '98', to: '692', texto: 'Dia 10' },
    { from: '98', to: '693', texto: 'Dia 11' },
    { from: '98', to: '694', texto: 'Dia 12' },
    { from: '98', to: '695', texto: 'Dia 13' },
    { from: '98', to: '696', texto: 'Dia 14' },
    { from: '98', to: '697', texto: 'Dia 15' },
    { from: '98', to: '698', texto: 'Dia 16' },
    { from: '98', to: '699', texto: 'Dia 17' },
    { from: '98', to: '2', texto: 'Dia 18' },
    { from: '98', to: '3', texto: 'Dia 18' },
    { from: '98', to: '203', texto: 'Dia 19' },
    { from: '98', to: '700', texto: 'Dia 20' },
    { from: '98', to: '701', texto: 'Dia 22' },
    { from: '98', to: '702', texto: 'Dia 23' },
    { from: '98', to: '703', texto: 'Dia 23' },
    { from: '98', to: '704', texto: 'Dia 24' },
    { from: '98', to: '705', texto: 'Dia 25' },
    { from: '98', to: '706', texto: 'Dia 26' },
    { from: '98', to: '707', texto: 'Dia 26' },
    { from: '98', to: '708', texto: 'Dia 29' },

    // Dezembro (99)
    { from: '99', to: '15',  texto: 'Dia 3' },
    { from: '99', to: '114', texto: 'Dia 21' },
    { from: '99', to: '55',  texto: 'Dia 27' },
    { from: '99', to: '709', texto: 'Dia 2' },
    { from: '99', to: '710', texto: 'Dia 4' },
    { from: '99', to: '711', texto: 'Dia 5' },
    { from: '99', to: '712', texto: 'Dia 6' },
    { from: '99', to: '713', texto: 'Dia 7' },
    { from: '99', to: '714', texto: 'Dia 10' },
    { from: '99', to: '715', texto: 'Dia 11' },
    { from: '99', to: '716', texto: 'Dia 13' },
    { from: '99', to: '717', texto: 'Dia 16' },
    { from: '99', to: '114', texto: 'Dia 19' },
    { from: '99', to: '630', texto: 'Dia 26' },
    { from: '99', to: '718', texto: 'Dia 28' },
    { from: '99', to: '719', texto: 'Dia 29' },
    { from: '99', to: '720', texto: 'Dia 31' },

    // ========== SANTOS -> LOCAIS (REGRAS DE LIGAÇÃO CUMPRIDAS) ==========
    { from: '4',   to: '130', title: 'nasceu em', texto: 'nasceu em' },
    { from: '71',  to: '131', title: 'pregou em', texto: 'pregou em' },
    { from: '2',   to: '26',  title: 'sede / martírio em', texto: 'sede / martírio em' },
    { from: '3',   to: '26',  title: 'martirizado em', texto: 'martirizado em' },
    { from: '55',  to: '132', title: 'atuou em', texto: 'atuou em' },
    { from: '86',  to: '133', title: 'martirizado em', texto: 'martirizado em' },
    { from: '110', to: '155', title: 'martirizado em', texto: 'martirizado em' },
    { from: '111', to: '156', title: 'venerado em', texto: 'venerado em' },
    { from: '112', to: '157', title: 'martirizado em', texto: 'martirizado em' },
    { from: '113', to: '158', title: 'martirizado em', texto: 'martirizado em' },
    { from: '114', to: '159', title: 'evangelizou', texto: 'evangelizou' },
    { from: '115', to: '160', title: 'evangelizou', texto: 'evangelizou' },
    { from: '116', to: '133', title: 'bispo de', texto: 'bispo de' },
    { from: '117', to: '161', title: 'martirizado em', texto: 'martirizado em' },
    { from: '118', to: '161', title: 'martirizado em', texto: 'martirizado em' },
    { from: '228', to: '314', title: 'martirizado em', texto: 'martirizado em' },
    { from: '215', to: '133', title: 'testemunhou em', texto: 'testemunhou em' },
    { from: '218', to: '130', title: 'venerada em', texto: 'venerada em' },
    { from: '221', to: '309', title: 'viveu em', texto: 'viveu em' },
    { from: '73',  to: '26',  title: 'martirizada em', texto: 'martirizada em' },
    { from: '72',  to: '26',  title: 'martirizado em', texto: 'martirizado em' },
    { from: '7',   to: '134', title: 'martirizado em', texto: 'martirizado em' },
    { from: '76',  to: '135', title: 'viveu em', texto: 'viveu em' },
    { from: '74',  to: '135', title: 'viveu em', texto: 'viveu em' },
    { from: '64',  to: '136', title: 'morreu em', texto: 'morreu em' },
    { from: '5',   to: '137', title: 'bispo de', texto: 'bispo de' },
    { from: '81',  to: '138', title: 'bispo de', texto: 'bispo de' },
    { from: '82',  to: '139', title: 'bispo de', texto: 'bispo de' },
    { from: '83',  to: '140', title: 'martirizada em', texto: 'martirizada em' },
    { from: '84',  to: '26',  title: 'martirizado em', texto: 'martirizado em' },
    { from: '204', to: '26',  title: 'martirizados em', texto: 'martirizados em' },
    { from: '205', to: '26',  title: 'sede em', texto: 'sede em' },
    { from: '207', to: '26',  title: 'sede em', texto: 'sede em' },
    { from: '210', to: '26',  title: 'viveu em', texto: 'viveu em' },
    { from: '214', to: '26',  title: 'martirizada em', texto: 'martirizada em' },
    { from: '216', to: '310', title: 'bispo de', texto: 'bispo de' },
    { from: '217', to: '307', title: 'martirizada em', texto: 'martirizada em' },
    { from: '219', to: '308', title: 'martirizado em', texto: 'martirizado em' },
    { from: '220', to: '300', title: 'martirizados em', texto: 'martirizados em' },
    { from: '222', to: '26',  title: 'martirizados em', texto: 'martirizados em' },
    { from: '223', to: '26',  title: 'martirizados em', texto: 'martirizados em' },
    { from: '226', to: '26',  title: 'martirizados em', texto: 'martirizados em' },
    { from: '230', to: '140', title: 'martirizados em', texto: 'martirizados em' },
    { from: '233', to: '300', title: 'martirizados em', texto: 'martirizados em' },
    { from: '234', to: '26',  title: 'morreu em', texto: 'morreu em' },
    { from: '237', to: '26',  title: 'martirizados em', texto: 'martirizados em' },
    { from: '6',   to: '141', title: 'fundou em', texto: 'fundou em' },
    { from: '85',  to: '141', title: 'viveu em', texto: 'viveu em' },
    { from: '66',  to: '142', title: 'abade de', texto: 'abade de' },
    { from: '8',   to: '143', title: 'nasceu em', texto: 'nasceu em' },
    { from: '11',  to: '143', title: 'viveu em', texto: 'viveu em' },
    { from: '9',   to: '144', title: 'morreu em', texto: 'morreu em' },
    { from: '10',  to: '145', title: 'ensinou em', texto: 'ensinou em' },
    { from: '65',  to: '146', title: 'morreu em', texto: 'morreu em' },
    { from: '67',  to: '147', title: 'viveu em', texto: 'viveu em' },
    { from: '200', to: '26',  title: 'sede em', texto: 'sede em' },
    { from: '202', to: '301', title: 'evangelizaram', texto: 'evangelizaram' },
    { from: '203', to: '302', title: 'rainha de', texto: 'rainha de' },
    { from: '206', to: '303', title: 'fundou em', texto: 'fundou em' },
    { from: '208', to: '304', title: 'morreu em', texto: 'morreu em' },
    { from: '209', to: '305', title: 'imperador de', texto: 'imperador de' },
    { from: '224', to: '311', title: 'bispo de', texto: 'bispo de' },
    { from: '225', to: '312', title: 'bispo de', texto: 'bispo de' },
    { from: '227', to: '313', title: 'rainha de', texto: 'rainha de' },
    { from: '229', to: '315', title: 'bispo de', texto: 'bispo de' },
    { from: '231', to: '316', title: 'diácono de', texto: 'diácono de' },
    { from: '232', to: '317', title: 'fundou em', texto: 'fundou em' },
    { from: '236', to: '318', title: 'bispo de', texto: 'bispo de' },
    { from: '238', to: '319', title: 'fundou em', texto: 'fundou em' },
    { from: '239', to: '304', title: 'bispo de', texto: 'bispo de' },
    { from: '14',  to: '26',  title: 'morreu em', texto: 'morreu em' },
    { from: '15',  to: '148', title: 'missionou em', texto: 'missionou em' },
    { from: '12',  to: '149', title: 'nasceu em', texto: 'nasceu em' },
    { from: '13',  to: '150', title: 'morreu em', texto: 'morreu em' },
    { from: '75',  to: '151', title: 'bispo de', texto: 'bispo de' },
    { from: '201', to: '300', title: 'fundou em', texto: 'fundou em' },
    { from: '211', to: '26',  title: 'morreu em', texto: 'morreu em' },
    { from: '212', to: '320', title: 'atuou em', texto: 'atuou em' },
    { from: '213', to: '306', title: 'fundou em', texto: 'fundou em' },
    { from: '235', to: '26',  title: 'morreu em', texto: 'morreu em' },
    { from: '16',  to: '152', title: 'pároco de', texto: 'pároco de' },
    { from: '61',  to: '153', title: 'fundou em', texto: 'fundou em' },
    { from: '17',  to: '154', title: 'viveu em', texto: 'viveu em' },
    { from: '19',  to: '26',  title: 'sede em', texto: 'sede em' },
    { from: '400', to: '26',  title: 'sede em', texto: 'sede em' },
    { from: '401', to: '500', title: 'bispo de', texto: 'bispo de' },
    { from: '402', to: '318', title: 'atuou em', texto: 'atuou em' },
    { from: '403', to: '501', title: 'abade em', texto: 'abade em' },
    { from: '404', to: '26',  title: 'sede em', texto: 'sede em' },
    { from: '405', to: '26',  title: 'martirizada em', texto: 'martirizada em' },
    { from: '406', to: '26',  title: 'martirizados em', texto: 'martirizados em' },
    { from: '407', to: '502', title: 'martirizado em', texto: 'martirizado em' },
    { from: '408', to: '26',  title: 'sede em', texto: 'sede em' },
    { from: '409', to: '503', title: 'martirizados em', texto: 'martirizados em' },
    { from: '410', to: '504', title: 'atuou em', texto: 'atuou em' },
    { from: '411', to: '26',  title: 'martirizada em', texto: 'martirizada em' },
    { from: '412', to: '132', title: 'bispo de', texto: 'bispo de' },
    { from: '413', to: '505', title: 'bispo de', texto: 'bispo de' },
    { from: '414', to: '506', title: 'bispo de', texto: 'bispo de' },
    { from: '415', to: '504', title: 'fundou em', texto: 'fundou em' },
    { from: '416', to: '26',  title: 'martirizada em', texto: 'martirizada em' },
    { from: '417', to: '507', title: 'bispo de', texto: 'bispo de' },
    { from: '418', to: '508', title: 'bispo de', texto: 'bispo de' },
    { from: '419', to: '315', title: 'martirizada em', texto: 'martirizada em' },
    { from: '420', to: '509', title: 'fundou em', texto: 'fundou em' },
    { from: '421', to: '26',  title: 'morreu em', texto: 'morreu em' },
    { from: '422', to: '510', title: 'bispo de', texto: 'bispo de' },
    { from: '423', to: '510', title: 'martirizada em', texto: 'martirizada em' },
    { from: '424', to: '511', title: 'venerada em', texto: 'venerada em' },
    { from: '425', to: '317', title: 'fundaram em', texto: 'fundaram em' },
    { from: '426', to: '512', title: 'martirizados em', texto: 'martirizados em' },
    { from: '427', to: '133', title: 'bispo de', texto: 'bispo de' },
    { from: '428', to: '513', title: 'abade de', texto: 'abade de' },
    { from: '429', to: '514', title: 'morreu em', texto: 'morreu em' },
    { from: '430', to: '515', title: 'morreu em', texto: 'morreu em' },
    { from: '431', to: '26',  title: 'sede em', texto: 'sede em' },
    { from: '432', to: '516', title: 'martirizadas em', texto: 'martirizadas em' },
    { from: '433', to: '517', title: 'fundou em', texto: 'fundou em' },
    { from: '434', to: '26',  title: 'viveu em', texto: 'viveu em' },
    { from: '435', to: '139', title: 'martirizados em', texto: 'martirizados em' },
    { from: '436', to: '26',  title: 'sede em', texto: 'sede em' },
    { from: '437', to: '518', title: 'evangelizou', texto: 'evangelizou' },
    { from: '438', to: '133', title: 'bispo de', texto: 'bispo de' },
    { from: '439', to: '26',  title: 'venerado em', texto: 'venerado em' },
    { from: '440', to: '130', title: 'ocorreu em', texto: 'ocorreu em' },
    { from: '441', to: '133', title: 'venerada em', texto: 'venerada em' },
    { from: '442', to: '519', title: 'viveu em', texto: 'viveu em' },
    { from: '443', to: '520', title: 'bispo de', texto: 'bispo de' },
    { from: '444', to: '521', title: 'nasceu em', texto: 'nasceu em' },
    { from: '445', to: '26',  title: 'sede em', texto: 'sede em' },
    { from: '446', to: '522', title: 'martirizado em', texto: 'martirizado em' },
    { from: '447', to: '26',  title: 'martirizado em', texto: 'martirizado em' },
    { from: '448', to: '26',  title: 'martirizados em', texto: 'martirizados em' },
    { from: '449', to: '26',  title: 'sede em', texto: 'sede em' },
    { from: '450', to: '523', title: 'bispo de', texto: 'bispo de' },
    { from: '451', to: '26',  title: 'sede em', texto: 'sede em' },
    { from: '452', to: '524', title: 'martirizado em', texto: 'martirizado em' },
    { from: '453', to: '525', title: 'venerado em', texto: 'venerado em' },
    { from: '454', to: '26',  title: 'sede em', texto: 'sede em' },
    { from: '455', to: '526', title: 'morreu em', texto: 'morreu em' },
    { from: '456', to: '26',  title: 'morreu em', texto: 'morreu em' },
    { from: '457', to: '310', title: 'martirizado em', texto: 'martirizado em' },
    { from: '458', to: '300', title: 'martirizado em', texto: 'martirizado em' },
    { from: '459', to: '527', title: 'viveu em', texto: 'viveu em' },

    // NOVOS SANTOS -> LOCAIS (Adicionado para não quebrar a regra de 100+ santos órfãos)
    { from: '600', to: '510', title: 'bispo de', texto: 'bispo de' },
    { from: '601', to: '26', title: 'sede em', texto: 'sede em' },
    { from: '602', to: '515', title: 'bispo de', texto: 'bispo de' },
    { from: '603', to: '26', title: 'venerado em', texto: 'venerado em' },
    { from: '604', to: '506', title: 'bispo de', texto: 'bispo de' },
    { from: '605', to: '317', title: 'bispo de', texto: 'bispo de' },
    { from: '606', to: '26', title: 'martirizados em', texto: 'martirizados em' },
    { from: '607', to: '26', title: 'martirizados em', texto: 'martirizados em' },
    { from: '608', to: '26', title: 'viveu em', texto: 'viveu em' },
    { from: '609', to: '801', title: 'apareceu em', texto: 'apareceu em' },
    { from: '610', to: '320', title: 'fundou em', texto: 'fundou em' },
    { from: '611', to: '26', title: 'viveu em', texto: 'viveu em' },
    { from: '612', to: '521', title: 'viveu em', texto: 'viveu em' },
    { from: '613', to: '26', title: 'martirizado em', texto: 'martirizado em' },
    { from: '614', to: '26', title: 'sede em', texto: 'sede em' },
    { from: '615', to: '26', title: 'martirizada em', texto: 'martirizada em' },
    { from: '616', to: '527', title: 'viveu em', texto: 'viveu em' },
    { from: '617', to: '26', title: 'sede em', texto: 'sede em' },
    { from: '618', to: '26', title: 'sede em', texto: 'sede em' },
    { from: '619', to: '26', title: 'atuou em', texto: 'atuou em' },
    { from: '620', to: '26', title: 'sede em', texto: 'sede em' },
    { from: '621', to: '523', title: 'viveu em', texto: 'viveu em' },
    { from: '622', to: '26', title: 'sede em', texto: 'sede em' },
    { from: '623', to: '523', title: 'bispo de', texto: 'bispo de' },
    { from: '624', to: '317', title: 'viveu em', texto: 'viveu em' },
    { from: '625', to: '26', title: 'sede em', texto: 'sede em' },
    { from: '626', to: '320', title: 'martirizada em', texto: 'martirizada em' },
    { from: '627', to: '520', title: 'viveu em', texto: 'viveu em' },
    { from: '628', to: '26', title: 'martirizada em', texto: 'martirizada em' },
    { from: '629', to: '145', title: 'fundou em', texto: 'fundou em' },
    { from: '630', to: '133', title: 'martirizado em', texto: 'martirizado em' },
    { from: '631', to: '26', title: 'venerada em', texto: 'venerada em' },
    { from: '632', to: '133', title: 'ocorreu em', texto: 'ocorreu em' },
    { from: '633', to: '145', title: 'fundou em', texto: 'fundou em' },
    { from: '634', to: '26', title: 'martirizados em', texto: 'martirizados em' },
    { from: '635', to: '26', title: 'martirizado em', texto: 'martirizado em' },
    { from: '636', to: '26', title: 'martirizados em', texto: 'martirizados em' },
    { from: '637', to: '26', title: 'martirizados em', texto: 'martirizados em' },
    { from: '638', to: '133', title: 'ocorreu em', texto: 'ocorreu em' },
    { from: '639', to: '130', title: 'viveu em', texto: 'viveu em' },
    { from: '640', to: '515', title: 'evangelizou', texto: 'evangelizou' },
    { from: '641', to: '26', title: 'martirizado em', texto: 'martirizado em' },
    { from: '642', to: '320', title: 'fundou em', texto: 'fundou em' },
    { from: '643', to: '151', title: 'fundou em', texto: 'fundou em' },
    { from: '644', to: '801', title: 'venerado em', texto: 'venerado em' },
    { from: '645', to: '317', title: 'viveu em', texto: 'viveu em' },
    { from: '646', to: '320', title: 'rei em', texto: 'rei em' },
    { from: '647', to: '26', title: 'sede em', texto: 'sede em' },
    { from: '648', to: '26', title: 'fundou em', texto: 'fundou em' },
    { from: '649', to: '145', title: 'viveu em', texto: 'viveu em' },
    { from: '650', to: '504', title: 'atuou em', texto: 'atuou em' },
    { from: '651', to: '320', title: 'abade de', texto: 'abade de' },
    { from: '652', to: '145', title: 'martirizados em', texto: 'martirizados em' },
    { from: '653', to: '301', title: 'rei em', texto: 'rei em' },
    { from: '654', to: '525', title: 'bispo de', texto: 'bispo de' },
    { from: '655', to: '308', title: 'martirizado em', texto: 'martirizado em' },
    { from: '656', to: '26', title: 'viveu em', texto: 'viveu em' },
    { from: '657', to: '26', title: 'martirizados em', texto: 'martirizados em' },
    { from: '658', to: '516', title: 'bispo/mártir em', texto: 'bispo/mártir em' },
    { from: '659', to: '26', title: 'viveu em', texto: 'viveu em' },
    { from: '660', to: '145', title: 'martirizados em', texto: 'martirizados em' },
    { from: '661', to: '26', title: 'martirizados em', texto: 'martirizados em' },
    { from: '662', to: '521', title: 'bispo de', texto: 'bispo de' },
    { from: '663', to: '151', title: 'martirizados em', texto: 'martirizados em' },
    { from: '664', to: '26', title: 'sede em', texto: 'sede em' },
    { from: '665', to: '138', title: 'martirizados em', texto: 'martirizados em' },
    { from: '666', to: '138', title: 'martirizados em', texto: 'martirizados em' },
    { from: '667', to: '301', title: 'rei em', texto: 'rei em' },
    { from: '668', to: '133', title: 'viveu em', texto: 'viveu em' },
    { from: '669', to: '320', title: 'bispo de', texto: 'bispo de' },
    { from: '670', to: '141', title: 'viveu em', texto: 'viveu em' },
    { from: '671', to: '141', title: 'fundou em', texto: 'fundou em' },
    { from: '672', to: '26', title: 'viveu em', texto: 'viveu em' },
    { from: '673', to: '26', title: 'fundou em', texto: 'fundou em' },
    { from: '674', to: '320', title: 'martirizados em', texto: 'martirizados em' },
    { from: '675', to: '26', title: 'viveu em', texto: 'viveu em' },
    { from: '676', to: '523', title: 'rei em', texto: 'rei em' },
    { from: '677', to: '26', title: 'sede em', texto: 'sede em' },
    { from: '678', to: '301', title: 'viveu em', texto: 'viveu em' },
    { from: '679', to: '320', title: 'viveu em', texto: 'viveu em' },
    { from: '680', to: '138', title: 'viveu em', texto: 'viveu em' },
    { from: '681', to: '149', title: 'viveu em', texto: 'viveu em' },
    { from: '682', to: '515', title: 'viveu em', texto: 'viveu em' },
    { from: '683', to: '133', title: 'viveu em', texto: 'viveu em' },
    { from: '684', to: '311', title: 'martirizadas em', texto: 'martirizadas em' },
    { from: '685', to: '130', title: 'venerado em', texto: 'venerado em' },
    { from: '686', to: '26', title: 'martirizados em', texto: 'martirizados em' },
    { from: '687', to: '26', title: 'sede em', texto: 'sede em' },
    { from: '688', to: '300', title: 'bispo de', texto: 'bispo de' },
    { from: '689', to: '320', title: 'viveu em', texto: 'viveu em' },
    { from: '690', to: '26', title: 'martirizados em', texto: 'martirizados em' },
    { from: '691', to: '157', title: 'martirizado em', texto: 'martirizado em' },
    { from: '692', to: '145', title: 'viveu em', texto: 'viveu em' },
    { from: '693', to: '800', title: 'bispo de', texto: 'bispo de' },
    { from: '694', to: '26', title: 'sede em', texto: 'sede em' },
    { from: '695', to: '503', title: 'viveu em', texto: 'viveu em' },
    { from: '696', to: '515', title: 'martirizado em', texto: 'martirizado em' },
    { from: '697', to: '312', title: 'viveu em', texto: 'viveu em' },
    { from: '698', to: '312', title: 'viveu em', texto: 'viveu em' },
    { from: '699', to: '315', title: 'bispo de', texto: 'bispo de' },
    { from: '700', to: '320', title: 'fundou em', texto: 'fundou em' },
    { from: '701', to: '26', title: 'martirizada em', texto: 'martirizada em' },
    { from: '702', to: '26', title: 'sede em', texto: 'sede em' },
    { from: '703', to: '26', title: 'martirizada em', texto: 'martirizada em' },
    { from: '704', to: '26', title: 'martirizado em', texto: 'martirizado em' },
    { from: '705', to: '510', title: 'martirizada em', texto: 'martirizada em' },
    { from: '706', to: '141', title: 'abade em', texto: 'abade em' },
    { from: '707', to: '510', title: 'bispo de', texto: 'bispo de' },
    { from: '708', to: '320', title: 'martirizado em', texto: 'martirizado em' },
    { from: '709', to: '26', title: 'martirizada em', texto: 'martirizada em' },
    { from: '710', to: '310', title: 'bispo de', texto: 'bispo de' },
    { from: '711', to: '133', title: 'abade em', texto: 'abade em' },
    { from: '712', to: '132', title: 'bispo de', texto: 'bispo de' },
    { from: '713', to: '300', title: 'bispo de', texto: 'bispo de' },
    { from: '714', to: '26', title: 'sede em', texto: 'sede em' },
    { from: '715', to: '26', title: 'sede em', texto: 'sede em' },
    { from: '716', to: '140', title: 'martirizada em', texto: 'martirizada em' },
    { from: '717', to: '26', title: 'martirizado em', texto: 'martirizado em' },
    { from: '718', to: '133', title: 'martirizados em', texto: 'martirizados em' },
    { from: '719', to: '523', title: 'bispo / martirizado em', texto: 'bispo / martirizado em' },
    { from: '720', to: '26', title: 'sede em', texto: 'sede em' },

    // CONGREGAÇÕES E OBRAS
    { from: '6', to: '22', title: 'fundou a', texto: 'fundou a' },
    { from: '85', to: '22', title: 'cofundou (ramo feminino)', texto: 'cofundou (ramo feminino)' },
    { from: '22', to: '63', title: 'gerou o ramo', texto: 'gerou o ramo' },
    { from: '8', to: '23', title: 'fundou a', texto: 'fundou a' },
    { from: '9', to: '24', title: 'fundou a', texto: 'fundou a' },
    { from: '14', to: '25', title: 'fundou a', texto: 'fundou a' },
    { from: '12', to: '41', title: 'reformou o', texto: 'reformou o' },
    { from: '61', to: '62', title: 'fundou a', texto: 'fundou a' },
    
    // Membros comuns (Dashed)
    { from: '66', to: '63', title: 'membro de', texto: 'membro de', dashes: true },
    { from: '11', to: '23', title: 'membro de', texto: 'membro de', dashes: true },
    { from: '65', to: '23', title: 'membro de', texto: 'membro de', dashes: true },
    { from: '10', to: '24', title: 'membro de', texto: 'membro de', dashes: true },
    { from: '15', to: '25', title: 'membro de', texto: 'membro de', dashes: true },
    { from: '13', to: '41', title: 'membro de', texto: 'membro de', dashes: true },
    { from: '17', to: '41', title: 'membro de', texto: 'membro de', dashes: true },
    { from: '235', to: '25', title: 'membro de', texto: 'membro de', dashes: true },
    { from: '410', to: '24', title: 'membro de', texto: 'membro de', dashes: true },
    { from: '444', to: '24', title: 'membro de', texto: 'membro de', dashes: true },
    { from: '455', to: '25', title: 'membro de', texto: 'membro de', dashes: true },
    { from: '458', to: '24', title: 'membro de', texto: 'membro de', dashes: true },
    { from: '459', to: '24', title: 'membro de', texto: 'membro de', dashes: true },
    { from: '608', to: '25', title: 'membro da', texto: 'membro da', dashes: true },
    { from: '675', to: '25', title: 'membro da', texto: 'membro da', dashes: true },
    { from: '616', to: '23', title: 'membro da', texto: 'membro da', dashes: true },
    { from: '681', to: '23', title: 'membro da', texto: 'membro da', dashes: true },
    { from: '697', to: '24', title: 'membro da', texto: 'membro da', dashes: true },
    { from: '624', to: '41', title: 'membro do', texto: 'membro do', dashes: true },

    // Obras / Parentescos
    { from: '10', to: '32', title: 'escreveu', texto: 'escreveu' },
    { from: '14', to: '34', title: 'escreveu', texto: 'escreveu' },
    { from: '12', to: '38', title: 'mestra de', texto: 'mestra de' },
    { from: '13', to: '38', title: 'mestre de', texto: 'mestre de' },
    { from: '64', to: '5', title: 'mãe de', texto: 'mãe de', dashes: true },
    { from: '75', to: '61', title: 'inspirou patronato', texto: 'inspirou patronato', dashes: true },
    { from: '85', to: '6', title: 'irmã de', texto: 'irmã de', dashes: true }
];
module.exports = { todosNos, todosSetas };
